//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2013_2014_mca
    {
        public int Sno { get; set; }
        public string CollegeCode { get; set; }
        public string CollegeName { get; set; }
        public Nullable<int> Student_Count { get; set; }
    }
}
