//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2014_15_bpharrmacy
    {
        public int SLNO { get; set; }
        public string CollegeName { get; set; }
        public string Code { get; set; }
        public Nullable<int> C2011_12 { get; set; }
        public Nullable<int> C2012_13 { get; set; }
        public Nullable<int> C2013_14 { get; set; }
        public Nullable<int> C2014_15 { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
