//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class college_faculty_2014_15
    {
        public int id { get; set; }
        public string collegeCode { get; set; }
        public string collegeName { get; set; }
        public string fatherName { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public string Category { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Qualification { get; set; }
        public string Specialization { get; set; }
        public string DateOfAppointment { get; set; }
        public string PreviousExperience { get; set; }
        public string isFacultyRatifiedByJNTU { get; set; }
        public string PayScale { get; set; }
        public string Basic { get; set; }
        public string NetSalary { get; set; }
        public string facultyType { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string remarks { get; set; }
        public bool isActive { get; set; }
    }
}
