//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_pgcourses
    {
        public int id { get; set; }
        public Nullable<int> collegeId { get; set; }
        public Nullable<int> specializationId { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<int> intake { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> professors { get; set; }
        public Nullable<int> associateProfessors { get; set; }
        public Nullable<int> assistantProfessors { get; set; }
        public string UGFacultyStudentRatio { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public string Type { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual jntuh_specialization jntuh_specialization { get; set; }
        public virtual jntuh_shift jntuh_shift { get; set; }
        public virtual jntuh_department jntuh_department { get; set; }
    }
}
