//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_facility_status
    {
        public jntuh_facility_status()
        {
            this.jntuh_college_land = new HashSet<jntuh_college_land>();
            this.jntuh_college_land1 = new HashSet<jntuh_college_land>();
        }
    
        public int id { get; set; }
        public string facilityStatus { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual ICollection<jntuh_college_land> jntuh_college_land { get; set; }
        public virtual ICollection<jntuh_college_land> jntuh_college_land1 { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
    }
}
