//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_area_requirement
    {
        public jntuh_area_requirement()
        {
            this.jntuh_college_area = new HashSet<jntuh_college_area>();
        }
    
        public int id { get; set; }
        public string areaType { get; set; }
        public string requirementType { get; set; }
        public Nullable<int> programId { get; set; }
        public Nullable<decimal> requiredRooms { get; set; }
        public string requiredRoomsCalculation { get; set; }
        public Nullable<decimal> requiredArea { get; set; }
        public string requiredAreaCalculation { get; set; }
        public string areaTypeDescription { get; set; }
        public int areaTypeDisplayOrder { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual jntuh_program_type jntuh_program_type { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual ICollection<jntuh_college_area> jntuh_college_area { get; set; }
    }
}
