//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_416randomcodes
    {
        public int Id { get; set; }
        public string Collegecode { get; set; }
        public int CollegeId { get; set; }
        public string Randomcode { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
