//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_designation
    {
        public jntuh_designation()
        {
            this.jntuh_college_antiragging_committee = new HashSet<jntuh_college_antiragging_committee>();
            this.jntuh_college_faculty = new HashSet<jntuh_college_faculty>();
            this.jntuh_college_grievance_committee = new HashSet<jntuh_college_grievance_committee>();
            this.jntuh_college_rti_details = new HashSet<jntuh_college_rti_details>();
            this.jntuh_college_women_protection_cell = new HashSet<jntuh_college_women_protection_cell>();
            this.jntuh_ffc_auditor = new HashSet<jntuh_ffc_auditor>();
            this.jntuh_registered_faculty_experience = new HashSet<jntuh_registered_faculty_experience>();
            this.jntuh_registered_faculty_experience_log = new HashSet<jntuh_registered_faculty_experience_log>();
            this.jntuh_registered_faculty = new HashSet<jntuh_registered_faculty>();
            this.jntuh_registered_faculty_oldfaculty = new HashSet<jntuh_registered_faculty_oldfaculty>();
            this.jntuh_reinspection_registered_faculty = new HashSet<jntuh_reinspection_registered_faculty>();
        }
    
        public int id { get; set; }
        public string designation { get; set; }
        public string designationDescription { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual ICollection<jntuh_college_antiragging_committee> jntuh_college_antiragging_committee { get; set; }
        public virtual ICollection<jntuh_college_faculty> jntuh_college_faculty { get; set; }
        public virtual ICollection<jntuh_college_grievance_committee> jntuh_college_grievance_committee { get; set; }
        public virtual ICollection<jntuh_college_rti_details> jntuh_college_rti_details { get; set; }
        public virtual ICollection<jntuh_college_women_protection_cell> jntuh_college_women_protection_cell { get; set; }
        public virtual ICollection<jntuh_ffc_auditor> jntuh_ffc_auditor { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual ICollection<jntuh_registered_faculty_experience> jntuh_registered_faculty_experience { get; set; }
        public virtual ICollection<jntuh_registered_faculty_experience_log> jntuh_registered_faculty_experience_log { get; set; }
        public virtual ICollection<jntuh_registered_faculty> jntuh_registered_faculty { get; set; }
        public virtual ICollection<jntuh_registered_faculty_oldfaculty> jntuh_registered_faculty_oldfaculty { get; set; }
        public virtual ICollection<jntuh_reinspection_registered_faculty> jntuh_reinspection_registered_faculty { get; set; }
    }
}
