//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_affliationstatus
    {
        public int SNO { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public string SpecializationName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> ISActive { get; set; }
    }
}
