//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_faculty_2013_14
    {
        public int id { get; set; }
        public Nullable<double> SNO { get; set; }
        public string CollegeCode { get; set; }
        public string CollegeName { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Qualification { get; set; }
        public Nullable<double> Exp { get; set; }
        public Nullable<double> DOA { get; set; }
        public string PayScale { get; set; }
        public string UR { get; set; }
        public string FileName { get; set; }
    }
}
