//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_feedback
    {
        public int id { get; set; }
        public string college { get; set; }
        public int stackholderId { get; set; }
        public string feedbackType { get; set; }
        public string subject { get; set; }
        public string fullName { get; set; }
        public string phoneNumber { get; set; }
        public string emailAddress { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
    
        public virtual jntuh_stackholder_type jntuh_stackholder_type { get; set; }
    }
}
