//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_land
    {
        public int id { get; set; }
        public int collegeId { get; set; }
        public decimal areaInAcres { get; set; }
        public int landTypeID { get; set; }
        public int landRegistrationTypeId { get; set; }
        public int landCategoryId { get; set; }
        public string conversionCertificateIssuedBy { get; set; }
        public Nullable<System.DateTime> conversionCertificateIssuedDate { get; set; }
        public string conversionCertificateIssuedPurpose { get; set; }
        public string buildingPlanIssuedBy { get; set; }
        public Nullable<System.DateTime> buildingPlanIssuedDate { get; set; }
        public string masterPlanIssuedBy { get; set; }
        public Nullable<System.DateTime> masterPlanIssuedDate { get; set; }
        public bool compoundWall { get; set; }
        public int approachRoadId { get; set; }
        public int powerSupplyId { get; set; }
        public int WaterSupplyId { get; set; }
        public int drinkingWaterId { get; set; }
        public bool IsPurifiedWater { get; set; }
        public int potableWaterPerDay { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual jntuh_approach_road jntuh_approach_road { get; set; }
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual jntuh_land_type jntuh_land_type { get; set; }
        public virtual jntuh_land_registration_type jntuh_land_registration_type { get; set; }
        public virtual jntuh_facility_status jntuh_facility_status { get; set; }
        public virtual jntuh_facility_status jntuh_facility_status1 { get; set; }
        public virtual jntuh_water_type jntuh_water_type { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual jntuh_land_category jntuh_land_category { get; set; }
    }
}
