//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_deficiencyrepoprt_college_pendingdocuments
    {
        public int Id { get; set; }
        public int CollegeId { get; set; }
        public string CollegeCode { get; set; }
        public string FFCTeamComments { get; set; }
        public Nullable<int> AICTENoOfFaculty { get; set; }
        public Nullable<bool> Antiraging { get; set; }
        public Nullable<bool> AuditedStatement { get; set; }
        public Nullable<bool> LandUsedCertificate { get; set; }
        public Nullable<int> Lastyearfaculty { get; set; }
        public Nullable<int> Currentyearfaculty { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
