//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_ffc_auditor
    {
        public jntuh_ffc_auditor()
        {
            this.jntuh_ffc_committee = new HashSet<jntuh_ffc_committee>();
        }
    
        public int id { get; set; }
        public string auditorName { get; set; }
        public Nullable<int> auditorDepartmentID { get; set; }
        public Nullable<int> auditorDesignationID { get; set; }
        public string auditorPreferredDesignation { get; set; }
        public string auditorEmail1 { get; set; }
        public string auditorEmail2 { get; set; }
        public string auditorMobile1 { get; set; }
        public string auditorMobile2 { get; set; }
        public string auditorPlace { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    
        public virtual jntuh_department jntuh_department { get; set; }
        public virtual jntuh_designation jntuh_designation { get; set; }
        public virtual ICollection<jntuh_ffc_committee> jntuh_ffc_committee { get; set; }
    }
}
