//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_library
    {
        public int id { get; set; }
        public int collegeId { get; set; }
        public string librarianName { get; set; }
        public string librarianQualifications { get; set; }
        public string libraryPhoneNumber { get; set; }
        public int totalSupportingStaff { get; set; }
        public int totalTitles { get; set; }
        public int totalVolumes { get; set; }
        public int totalNationalJournals { get; set; }
        public int totalInternationalJournals { get; set; }
        public int totalEJournals { get; set; }
        public int librarySeatingCapacity { get; set; }
        public int libraryWorkingHoursFrom { get; set; }
        public int libraryWorkingHoursTo { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
    }
}
