//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_auditors_dataentry
    {
        public int Id { get; set; }
        public int CollegeId { get; set; }
        public int SpecializationId { get; set; }
        public int DepartmentId { get; set; }
        public int DegreeId { get; set; }
        public string RegistrationNo { get; set; }
        public int AuditorId { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string SCMhardcopy { get; set; }
    }
}
