//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_ffc_cluster_emails
    {
        public int id { get; set; }
        public int collegeId { get; set; }
        public string emailSubject { get; set; }
        public string emailBody { get; set; }
        public string emailTo { get; set; }
        public string smsText { get; set; }
        public string smsTo { get; set; }
        public System.DateTime createdOn { get; set; }
        public int createdBy { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
    }
}
