//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_intake_existing_log
    {
        public int LogId { get; set; }
        public int id { get; set; }
        public int academicYearId { get; set; }
        public int collegeId { get; set; }
        public int specializationId { get; set; }
        public int shiftId { get; set; }
        public int approvedIntake { get; set; }
        public int admittedIntake { get; set; }
        public Nullable<int> proposedIntake { get; set; }
        public string approvalLetter { get; set; }
        public Nullable<System.DateTime> nbaFrom { get; set; }
        public Nullable<System.DateTime> nbaTo { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public string courseStatus { get; set; }
        public bool courseAffiliatedStatus { get; set; }
    }
}
