//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_bpharmacy_faculty_deficiency
    {
        public int Id { get; set; }
        public int CollegeId { get; set; }
        public int SpecializationId { get; set; }
        public string BpharmacySpecialization { get; set; }
        public int ShiftId { get; set; }
        public Nullable<int> SpecializationWiseFaculty { get; set; }
        public bool Deficiency { get; set; }
        public int Shortage { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
