//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_ffc_schedule
    {
        public jntuh_ffc_schedule()
        {
            this.jntuh_ffc_committee = new HashSet<jntuh_ffc_committee>();
            this.jntuh_ffc_order = new HashSet<jntuh_ffc_order>();
        }
    
        public int id { get; set; }
        public Nullable<int> collegeID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> inspectionDate { get; set; }
        public Nullable<System.DateTime> alternateInspectionDate { get; set; }
        public Nullable<int> isRevisedOrder { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> InspectionPhaseId { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual ICollection<jntuh_ffc_committee> jntuh_ffc_committee { get; set; }
        public virtual ICollection<jntuh_ffc_order> jntuh_ffc_order { get; set; }
    }
}
