//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_lab_master
    {
        public jntuh_lab_master()
        {
            this.jntuh_college_laboratories = new HashSet<jntuh_college_laboratories>();
            this.jntuh_college_laboratories_dataentry2 = new HashSet<jntuh_college_laboratories_dataentry2>();
            this.jntuh_reinspection_college_laboratories = new HashSet<jntuh_reinspection_college_laboratories>();
        }
    
        public int id { get; set; }
        public int DegreeID { get; set; }
        public int DepartmentID { get; set; }
        public int SpecializationID { get; set; }
        public int Year { get; set; }
        public Nullable<int> Semester { get; set; }
        public string Labcode { get; set; }
        public string LabName { get; set; }
        public string EquipmentName { get; set; }
        public string Remarks { get; set; }
        public string noofUnits { get; set; }
        public string ExperimentsIds { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual ICollection<jntuh_college_laboratories> jntuh_college_laboratories { get; set; }
        public virtual ICollection<jntuh_college_laboratories_dataentry2> jntuh_college_laboratories_dataentry2 { get; set; }
        public virtual jntuh_degree jntuh_degree { get; set; }
        public virtual jntuh_department jntuh_department { get; set; }
        public virtual jntuh_specialization jntuh_specialization { get; set; }
        public virtual ICollection<jntuh_reinspection_college_laboratories> jntuh_reinspection_college_laboratories { get; set; }
    }
}
