//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_applications
    {
        public my_aspnet_applications()
        {
            this.my_aspnet_sessions = new HashSet<my_aspnet_sessions>();
            this.my_aspnet_users = new HashSet<my_aspnet_users>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual my_aspnet_sessioncleanup my_aspnet_sessioncleanup { get; set; }
        public virtual ICollection<my_aspnet_sessions> my_aspnet_sessions { get; set; }
        public virtual ICollection<my_aspnet_users> my_aspnet_users { get; set; }
    }
}
