//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_sessioncleanup
    {
        public System.DateTime LastRun { get; set; }
        public int IntervalMinutes { get; set; }
        public int ApplicationId { get; set; }
    
        public virtual my_aspnet_applications my_aspnet_applications { get; set; }
    }
}
