//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class pan_tptalpansstatus
    {
        public double ID { get; set; }
        public string PAN { get; set; }
        public string PAN_STATUS { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string TITLE { get; set; }
        public string LASTUPDATED { get; set; }
        public string FILLER1 { get; set; }
        public string FILLER2 { get; set; }
        public string FILLER3 { get; set; }
        public Nullable<System.DateTime> CREATEDDATA { get; set; }
    }
}
