//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASDATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_jntuh_totalcollegesassociatedfacultyfaculty
    {
        public int ID { get; set; }
        public string FType { get; set; }
        public Nullable<int> Collegeid { get; set; }
        public string collegeCode { get; set; }
        public string RegistrationNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string departmentName { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> DateOfAppointment { get; set; }
        public Nullable<bool> Absent { get; set; }
        public Nullable<bool> NoForm16 { get; set; }
        public Nullable<bool> NoSCM { get; set; }
        public Nullable<bool> FalsePAN { get; set; }
        public Nullable<bool> NotQualifiedAsperAICTE { get; set; }
        public Nullable<bool> PHDundertakingnotsubmitted { get; set; }
        public Nullable<bool> Notin116 { get; set; }
        public Nullable<bool> Blacklistfaculy { get; set; }
        public string EducationQulification { get; set; }
        public Nullable<int> DesignationId { get; set; }
    }
}
