//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aadhaarnumbernotexistsinlive
    {
        public int SNO { get; set; }
        public string RegistrationNumber { get; set; }
        public string AadhaarNumber { get; set; }
        public Nullable<short> FacultyStatus { get; set; }
    }
}
