//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admittedintake
    {
        public int Sno { get; set; }
        public string CollegeCode { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public Nullable<int> collegeId { get; set; }
        public Nullable<int> Intake201415 { get; set; }
        public Nullable<int> Intake201516 { get; set; }
        public Nullable<int> Intake201617 { get; set; }
    }
}
