//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_college_emails
    {
        public int id { get; set; }
        public string CollegeName { get; set; }
        public string Code { get; set; }
        public string PrincipalName { get; set; }
        public string Email { get; set; }
        public Nullable<double> Mobile { get; set; }
        public string Username { get; set; }
    }
}
