//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collegesintake
    {
        public int Id { get; set; }
        public string Collegecode { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> Intake { get; set; }
        public string IntakeYear { get; set; }
        public Nullable<int> ExcelOrder { get; set; }
    }
}
