//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collegefaculty_1
    {
        public int SNO { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public string collegeCode { get; set; }
        public string collegeName { get; set; }
        public string RegistrationNumber { get; set; }
        public string FacultyName { get; set; }
        public string AadhaarNumber { get; set; }
        public string designation { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public string departmentid { get; set; }
    }
}
