//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class committeemembers2015
    {
        public int SNo { get; set; }
        public string CC { get; set; }
        public string CollegeName { get; set; }
        public string Mandal { get; set; }
        public string District { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TeamMember1 { get; set; }
        public string TeamMember2 { get; set; }
        public string TeamMember3 { get; set; }
        public string TeamMember4 { get; set; }
        public string ScrutinyBy { get; set; }
        public string Scanned { get; set; }
    }
}
