//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facultyanalysis_2013_14_count
    {
        public int Sno { get; set; }
        public string Code { get; set; }
        public string CollegeName { get; set; }
        public Nullable<double> Count { get; set; }
    }
}
