//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facultyanalysis_2014_15
    {
        public int SNo { get; set; }
        public string Code { get; set; }
        public string CollegeName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Surname { get; set; }
        public string Father { get; set; }
        public string DOA { get; set; }
        public string DateOfBirth { get; set; }
        public string Facultyinothercolleges { get; set; }
    }
}
