//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_academic_year
    {
        public jntuh_academic_year()
        {
            this.jntuh_college_academic_performance = new HashSet<jntuh_college_academic_performance>();
            this.jntuh_college_batch_performance = new HashSet<jntuh_college_batch_performance>();
            this.jntuh_college_fee_reimbursement = new HashSet<jntuh_college_fee_reimbursement>();
            this.jntuh_college_intake_existing = new HashSet<jntuh_college_intake_existing>();
            this.jntuh_college_intake_existing_datentry2 = new HashSet<jntuh_college_intake_existing_datentry2>();
            this.jntuh_college_intake_proposed = new HashSet<jntuh_college_intake_proposed>();
            this.jntuh_college_overall_faculty_studentratio = new HashSet<jntuh_college_overall_faculty_studentratio>();
            this.jntuh_college_placement = new HashSet<jntuh_college_placement>();
            this.jntuh_inspection_phase = new HashSet<jntuh_inspection_phase>();
        }
    
        public int id { get; set; }
        public string academicYear { get; set; }
        public int actualYear { get; set; }
        public bool isPresentAcademicYear { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual ICollection<jntuh_college_academic_performance> jntuh_college_academic_performance { get; set; }
        public virtual ICollection<jntuh_college_batch_performance> jntuh_college_batch_performance { get; set; }
        public virtual ICollection<jntuh_college_fee_reimbursement> jntuh_college_fee_reimbursement { get; set; }
        public virtual ICollection<jntuh_college_intake_existing> jntuh_college_intake_existing { get; set; }
        public virtual ICollection<jntuh_college_intake_existing_datentry2> jntuh_college_intake_existing_datentry2 { get; set; }
        public virtual ICollection<jntuh_college_intake_proposed> jntuh_college_intake_proposed { get; set; }
        public virtual ICollection<jntuh_college_overall_faculty_studentratio> jntuh_college_overall_faculty_studentratio { get; set; }
        public virtual ICollection<jntuh_college_placement> jntuh_college_placement { get; set; }
        public virtual ICollection<jntuh_inspection_phase> jntuh_inspection_phase { get; set; }
    }
}
