//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_faculty_verified
    {
        public int Id { get; set; }
        public int FacultyId { get; set; }
        public int LabelId { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public int VerificationOfficer { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual jntuh_college_faculty_registered jntuh_college_faculty_registered { get; set; }
        public virtual jntuh_registered_faculty_labels jntuh_registered_faculty_labels { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
    }
}
