//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_dates
    {
        public int id { get; set; }
        public string collegecode { get; set; }
        public string collegeName { get; set; }
        public Nullable<System.DateTime> applicationDate { get; set; }
        public Nullable<System.DateTime> deficiencyLetterDate { get; set; }
        public Nullable<System.DateTime> hearingDate { get; set; }
    }
}
