//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_auditor_assigned
    {
        public int Id { get; set; }
        public int ScmId { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public int AuditorId { get; set; }
        public string OldAuditorIds { get; set; }
        public string SCMListPath { get; set; }
        public Nullable<System.DateTime> RequestSubmittedDate { get; set; }
        public Nullable<System.DateTime> NomineeReassignDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
