//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_settings
    {
        public bool isLive { get; set; }
        public string testEmail { get; set; }
        public string testMobile { get; set; }
        public string testEmailThroughCC { get; set; }
    }
}
