//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_registered_faculty_noscmold
    {
        public long ID { get; set; }
        public string Registrationnumber { get; set; }
        public Nullable<bool> NOSCM { get; set; }
    }
}
