//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college
    {
        public jntuh_college()
        {
            this.college_circulars = new HashSet<college_circulars>();
            this.college_clusters = new HashSet<college_clusters>();
            this.college_grade = new HashSet<college_grade>();
            this.college_undertaking = new HashSet<college_undertaking>();
            this.jntuh_address = new HashSet<jntuh_address>();
            this.jntuh_college_academic_performance_points = new HashSet<jntuh_college_academic_performance_points>();
            this.jntuh_college_committee_observations = new HashSet<jntuh_college_committee_observations>();
            this.jntuh_college_faculty_deficiency = new HashSet<jntuh_college_faculty_deficiency>();
            this.jntuh_college_funds = new HashSet<jntuh_college_funds>();
            this.jntuh_college_infrastructure_parameters = new HashSet<jntuh_college_infrastructure_parameters>();
            this.jntuh_college_laboratories = new HashSet<jntuh_college_laboratories>();
            this.jntuh_college_laboratories_dataentry2 = new HashSet<jntuh_college_laboratories_dataentry2>();
            this.jntuh_college_laboratories_deficiency = new HashSet<jntuh_college_laboratories_deficiency>();
            this.jntuh_college_miscellaneous_parameters = new HashSet<jntuh_college_miscellaneous_parameters>();
            this.jntuh_college_pgcourses = new HashSet<jntuh_college_pgcourses>();
            this.jntuh_college_randamcodes = new HashSet<jntuh_college_randamcodes>();
            this.jntuh_college_screens_assigned = new HashSet<jntuh_college_screens_assigned>();
            this.jntuh_college_screens_assigned_log = new HashSet<jntuh_college_screens_assigned_log>();
            this.jntuh_college_staticdata_modifications = new HashSet<jntuh_college_staticdata_modifications>();
            this.jntuh_committee_submission = new HashSet<jntuh_committee_submission>();
            this.jntuh_dataentry_allotment = new HashSet<jntuh_dataentry_allotment>();
            this.jntuh_ffc_schedule = new HashSet<jntuh_ffc_schedule>();
            this.jntuh_reinspection_college_laboratories = new HashSet<jntuh_reinspection_college_laboratories>();
            this.jntuh_reinspection_college_laboratories_deficiency = new HashSet<jntuh_reinspection_college_laboratories_deficiency>();
            this.jntuh_college_academic_performance = new HashSet<jntuh_college_academic_performance>();
            this.jntuh_college_affiliation = new HashSet<jntuh_college_affiliation>();
            this.jntuh_college_antiragging_committee = new HashSet<jntuh_college_antiragging_committee>();
            this.jntuh_college_antiragging_complaints = new HashSet<jntuh_college_antiragging_complaints>();
            this.jntuh_college_area = new HashSet<jntuh_college_area>();
            this.jntuh_college_chairperson = new HashSet<jntuh_college_chairperson>();
            this.jntuh_college_closure = new HashSet<jntuh_college_closure>();
            this.jntuh_college_computer_lab = new HashSet<jntuh_college_computer_lab>();
            this.jntuh_college_computer_lab_printers = new HashSet<jntuh_college_computer_lab_printers>();
            this.jntuh_college_computer_student_ratio = new HashSet<jntuh_college_computer_student_ratio>();
            this.jntuh_college_degree = new HashSet<jntuh_college_degree>();
            this.jntuh_college_desirable_others = new HashSet<jntuh_college_desirable_others>();
            this.jntuh_college_desirable_requirement = new HashSet<jntuh_college_desirable_requirement>();
            this.jntuh_college_document = new HashSet<jntuh_college_document>();
            this.jntuh_college_edit_remarks = new HashSet<jntuh_college_edit_remarks>();
            this.jntuh_college_edit_status = new HashSet<jntuh_college_edit_status>();
            this.jntuh_college_edit_status_log = new HashSet<jntuh_college_edit_status_log>();
            this.jntuh_college_enclosures = new HashSet<jntuh_college_enclosures>();
            this.jntuh_college_enclosures_hardcopy = new HashSet<jntuh_college_enclosures_hardcopy>();
            this.jntuh_college_establishment = new HashSet<jntuh_college_establishment>();
            this.jntuh_college_examination_branch_edep = new HashSet<jntuh_college_examination_branch_edep>();
            this.jntuh_college_examination_branch = new HashSet<jntuh_college_examination_branch>();
            this.jntuh_college_examination_branch_security = new HashSet<jntuh_college_examination_branch_security>();
            this.jntuh_college_examination_branch_staff = new HashSet<jntuh_college_examination_branch_staff>();
            this.jntuh_college_expenditure = new HashSet<jntuh_college_expenditure>();
            this.jntuh_college_faculty = new HashSet<jntuh_college_faculty>();
            this.jntuh_college_faculty_registered = new HashSet<jntuh_college_faculty_registered>();
            this.jntuh_college_faculty_student_ratio = new HashSet<jntuh_college_faculty_student_ratio>();
            this.jntuh_college_fee_reimbursement = new HashSet<jntuh_college_fee_reimbursement>();
            this.jntuh_college_ffc_overall_faculty_studentratio = new HashSet<jntuh_college_ffc_overall_faculty_studentratio>();
            this.jntuh_college_grievance_committee = new HashSet<jntuh_college_grievance_committee>();
            this.jntuh_college_grievance_complaints = new HashSet<jntuh_college_grievance_complaints>();
            this.jntuh_college_hostel_maintenance = new HashSet<jntuh_college_hostel_maintenance>();
            this.jntuh_college_income = new HashSet<jntuh_college_income>();
            this.jntuh_college_intake_existing = new HashSet<jntuh_college_intake_existing>();
            this.jntuh_college_intake_existing_datentry2 = new HashSet<jntuh_college_intake_existing_datentry2>();
            this.jntuh_college_intake_proposed = new HashSet<jntuh_college_intake_proposed>();
            this.jntuh_college_internet_bandwidth = new HashSet<jntuh_college_internet_bandwidth>();
            this.jntuh_college_lab = new HashSet<jntuh_college_lab>();
            this.jntuh_college_land = new HashSet<jntuh_college_land>();
            this.jntuh_college_legal_software = new HashSet<jntuh_college_legal_software>();
            this.jntuh_college_library = new HashSet<jntuh_college_library>();
            this.jntuh_college_library_details = new HashSet<jntuh_college_library_details>();
            this.jntuh_college_name_change = new HashSet<jntuh_college_name_change>();
            this.jntuh_college_news = new HashSet<jntuh_college_news>();
            this.jntuh_college_news_old = new HashSet<jntuh_college_news_old>();
            this.jntuh_college_other_university_courses = new HashSet<jntuh_college_other_university_courses>();
            this.jntuh_college_overall_faculty_studentratio = new HashSet<jntuh_college_overall_faculty_studentratio>();
            this.jntuh_college_payment = new HashSet<jntuh_college_payment>();
            this.jntuh_college_paymentoffee = new HashSet<jntuh_college_paymentoffee>();
            this.jntuh_college_placement = new HashSet<jntuh_college_placement>();
            this.jntuh_college_principal_director = new HashSet<jntuh_college_principal_director>();
            this.jntuh_college_principal_ratified = new HashSet<jntuh_college_principal_ratified>();
            this.jntuh_college_principal_registered = new HashSet<jntuh_college_principal_registered>();
            this.jntuh_college_rti_complaints = new HashSet<jntuh_college_rti_complaints>();
            this.jntuh_college_rti_details = new HashSet<jntuh_college_rti_details>();
            this.jntuh_college_sports = new HashSet<jntuh_college_sports>();
            this.jntuh_college_teaching_faculty_position = new HashSet<jntuh_college_teaching_faculty_position>();
            this.jntuh_college_users = new HashSet<jntuh_college_users>();
            this.jntuh_college_women_protection_cell = new HashSet<jntuh_college_women_protection_cell>();
            this.jntuh_college_women_protection_cell_complaints = new HashSet<jntuh_college_women_protection_cell_complaints>();
            this.jntuh_ffc_cluster_emails = new HashSet<jntuh_ffc_cluster_emails>();
            this.jntuh_registered_faculty_experience = new HashSet<jntuh_registered_faculty_experience>();
            this.jntuh_registered_faculty_experience_log = new HashSet<jntuh_registered_faculty_experience_log>();
            this.jntuh_society_other_colleges = new HashSet<jntuh_society_other_colleges>();
            this.jntuh_society_other_locations_colleges = new HashSet<jntuh_society_other_locations_colleges>();
        }
    
        public int id { get; set; }
        public string collegeCode { get; set; }
        public string collegeName { get; set; }
        public int collegeTypeID { get; set; }
        public int collegeStatusID { get; set; }
        public string societyName { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public string eamcetCode { get; set; }
        public string icetCode { get; set; }
        public int collegeAffiliationTypeID { get; set; }
        public string otherCategory { get; set; }
        public bool isClosed { get; set; }
        public bool isDeleted { get; set; }
        public bool isPermant { get; set; }
        public bool isNew { get; set; }
    
        public virtual ICollection<college_circulars> college_circulars { get; set; }
        public virtual ICollection<college_clusters> college_clusters { get; set; }
        public virtual ICollection<college_grade> college_grade { get; set; }
        public virtual ICollection<college_undertaking> college_undertaking { get; set; }
        public virtual ICollection<jntuh_address> jntuh_address { get; set; }
        public virtual ICollection<jntuh_college_academic_performance_points> jntuh_college_academic_performance_points { get; set; }
        public virtual ICollection<jntuh_college_committee_observations> jntuh_college_committee_observations { get; set; }
        public virtual ICollection<jntuh_college_faculty_deficiency> jntuh_college_faculty_deficiency { get; set; }
        public virtual ICollection<jntuh_college_funds> jntuh_college_funds { get; set; }
        public virtual ICollection<jntuh_college_infrastructure_parameters> jntuh_college_infrastructure_parameters { get; set; }
        public virtual ICollection<jntuh_college_laboratories> jntuh_college_laboratories { get; set; }
        public virtual ICollection<jntuh_college_laboratories_dataentry2> jntuh_college_laboratories_dataentry2 { get; set; }
        public virtual ICollection<jntuh_college_laboratories_deficiency> jntuh_college_laboratories_deficiency { get; set; }
        public virtual ICollection<jntuh_college_miscellaneous_parameters> jntuh_college_miscellaneous_parameters { get; set; }
        public virtual ICollection<jntuh_college_pgcourses> jntuh_college_pgcourses { get; set; }
        public virtual ICollection<jntuh_college_randamcodes> jntuh_college_randamcodes { get; set; }
        public virtual ICollection<jntuh_college_screens_assigned> jntuh_college_screens_assigned { get; set; }
        public virtual ICollection<jntuh_college_screens_assigned_log> jntuh_college_screens_assigned_log { get; set; }
        public virtual ICollection<jntuh_college_staticdata_modifications> jntuh_college_staticdata_modifications { get; set; }
        public virtual ICollection<jntuh_committee_submission> jntuh_committee_submission { get; set; }
        public virtual ICollection<jntuh_dataentry_allotment> jntuh_dataentry_allotment { get; set; }
        public virtual ICollection<jntuh_ffc_schedule> jntuh_ffc_schedule { get; set; }
        public virtual ICollection<jntuh_reinspection_college_laboratories> jntuh_reinspection_college_laboratories { get; set; }
        public virtual ICollection<jntuh_reinspection_college_laboratories_deficiency> jntuh_reinspection_college_laboratories_deficiency { get; set; }
        public virtual ICollection<jntuh_college_academic_performance> jntuh_college_academic_performance { get; set; }
        public virtual ICollection<jntuh_college_affiliation> jntuh_college_affiliation { get; set; }
        public virtual ICollection<jntuh_college_antiragging_committee> jntuh_college_antiragging_committee { get; set; }
        public virtual ICollection<jntuh_college_antiragging_complaints> jntuh_college_antiragging_complaints { get; set; }
        public virtual ICollection<jntuh_college_area> jntuh_college_area { get; set; }
        public virtual ICollection<jntuh_college_chairperson> jntuh_college_chairperson { get; set; }
        public virtual ICollection<jntuh_college_closure> jntuh_college_closure { get; set; }
        public virtual ICollection<jntuh_college_computer_lab> jntuh_college_computer_lab { get; set; }
        public virtual ICollection<jntuh_college_computer_lab_printers> jntuh_college_computer_lab_printers { get; set; }
        public virtual ICollection<jntuh_college_computer_student_ratio> jntuh_college_computer_student_ratio { get; set; }
        public virtual ICollection<jntuh_college_degree> jntuh_college_degree { get; set; }
        public virtual ICollection<jntuh_college_desirable_others> jntuh_college_desirable_others { get; set; }
        public virtual ICollection<jntuh_college_desirable_requirement> jntuh_college_desirable_requirement { get; set; }
        public virtual ICollection<jntuh_college_document> jntuh_college_document { get; set; }
        public virtual ICollection<jntuh_college_edit_remarks> jntuh_college_edit_remarks { get; set; }
        public virtual ICollection<jntuh_college_edit_status> jntuh_college_edit_status { get; set; }
        public virtual ICollection<jntuh_college_edit_status_log> jntuh_college_edit_status_log { get; set; }
        public virtual ICollection<jntuh_college_enclosures> jntuh_college_enclosures { get; set; }
        public virtual ICollection<jntuh_college_enclosures_hardcopy> jntuh_college_enclosures_hardcopy { get; set; }
        public virtual ICollection<jntuh_college_establishment> jntuh_college_establishment { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_edep> jntuh_college_examination_branch_edep { get; set; }
        public virtual ICollection<jntuh_college_examination_branch> jntuh_college_examination_branch { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_security> jntuh_college_examination_branch_security { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_staff> jntuh_college_examination_branch_staff { get; set; }
        public virtual ICollection<jntuh_college_expenditure> jntuh_college_expenditure { get; set; }
        public virtual ICollection<jntuh_college_faculty> jntuh_college_faculty { get; set; }
        public virtual ICollection<jntuh_college_faculty_registered> jntuh_college_faculty_registered { get; set; }
        public virtual ICollection<jntuh_college_faculty_student_ratio> jntuh_college_faculty_student_ratio { get; set; }
        public virtual ICollection<jntuh_college_fee_reimbursement> jntuh_college_fee_reimbursement { get; set; }
        public virtual ICollection<jntuh_college_ffc_overall_faculty_studentratio> jntuh_college_ffc_overall_faculty_studentratio { get; set; }
        public virtual ICollection<jntuh_college_grievance_committee> jntuh_college_grievance_committee { get; set; }
        public virtual ICollection<jntuh_college_grievance_complaints> jntuh_college_grievance_complaints { get; set; }
        public virtual ICollection<jntuh_college_hostel_maintenance> jntuh_college_hostel_maintenance { get; set; }
        public virtual jntuh_college_type jntuh_college_type { get; set; }
        public virtual jntuh_college_status jntuh_college_status { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual jntuh_college_affiliation_type jntuh_college_affiliation_type { get; set; }
        public virtual ICollection<jntuh_college_income> jntuh_college_income { get; set; }
        public virtual ICollection<jntuh_college_intake_existing> jntuh_college_intake_existing { get; set; }
        public virtual ICollection<jntuh_college_intake_existing_datentry2> jntuh_college_intake_existing_datentry2 { get; set; }
        public virtual ICollection<jntuh_college_intake_proposed> jntuh_college_intake_proposed { get; set; }
        public virtual ICollection<jntuh_college_internet_bandwidth> jntuh_college_internet_bandwidth { get; set; }
        public virtual ICollection<jntuh_college_lab> jntuh_college_lab { get; set; }
        public virtual ICollection<jntuh_college_land> jntuh_college_land { get; set; }
        public virtual ICollection<jntuh_college_legal_software> jntuh_college_legal_software { get; set; }
        public virtual ICollection<jntuh_college_library> jntuh_college_library { get; set; }
        public virtual ICollection<jntuh_college_library_details> jntuh_college_library_details { get; set; }
        public virtual ICollection<jntuh_college_name_change> jntuh_college_name_change { get; set; }
        public virtual ICollection<jntuh_college_news> jntuh_college_news { get; set; }
        public virtual ICollection<jntuh_college_news_old> jntuh_college_news_old { get; set; }
        public virtual ICollection<jntuh_college_other_university_courses> jntuh_college_other_university_courses { get; set; }
        public virtual ICollection<jntuh_college_overall_faculty_studentratio> jntuh_college_overall_faculty_studentratio { get; set; }
        public virtual ICollection<jntuh_college_payment> jntuh_college_payment { get; set; }
        public virtual ICollection<jntuh_college_paymentoffee> jntuh_college_paymentoffee { get; set; }
        public virtual ICollection<jntuh_college_placement> jntuh_college_placement { get; set; }
        public virtual ICollection<jntuh_college_principal_director> jntuh_college_principal_director { get; set; }
        public virtual ICollection<jntuh_college_principal_ratified> jntuh_college_principal_ratified { get; set; }
        public virtual ICollection<jntuh_college_principal_registered> jntuh_college_principal_registered { get; set; }
        public virtual ICollection<jntuh_college_rti_complaints> jntuh_college_rti_complaints { get; set; }
        public virtual ICollection<jntuh_college_rti_details> jntuh_college_rti_details { get; set; }
        public virtual ICollection<jntuh_college_sports> jntuh_college_sports { get; set; }
        public virtual ICollection<jntuh_college_teaching_faculty_position> jntuh_college_teaching_faculty_position { get; set; }
        public virtual ICollection<jntuh_college_users> jntuh_college_users { get; set; }
        public virtual ICollection<jntuh_college_women_protection_cell> jntuh_college_women_protection_cell { get; set; }
        public virtual ICollection<jntuh_college_women_protection_cell_complaints> jntuh_college_women_protection_cell_complaints { get; set; }
        public virtual ICollection<jntuh_ffc_cluster_emails> jntuh_ffc_cluster_emails { get; set; }
        public virtual ICollection<jntuh_registered_faculty_experience> jntuh_registered_faculty_experience { get; set; }
        public virtual ICollection<jntuh_registered_faculty_experience_log> jntuh_registered_faculty_experience_log { get; set; }
        public virtual ICollection<jntuh_society_other_colleges> jntuh_society_other_colleges { get; set; }
        public virtual ICollection<jntuh_society_other_locations_colleges> jntuh_society_other_locations_colleges { get; set; }
    }
}
