//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_paymentrequests
    {
        public long Id { get; set; }
        public string CollegeCode { get; set; }
        public string ChallanNumber { get; set; }
        public System.DateTime TxnDate { get; set; }
        public string MerchantID { get; set; }
        public string CustomerID { get; set; }
        public decimal TxnAmount { get; set; }
        public string CurrencyType { get; set; }
        public string SecurityID { get; set; }
        public string PaymentType { get; set; }
    }
}
