//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_physical_labmaster_copy
    {
        public int Id { get; set; }
        public int Collegeid { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Semister { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public string Labcode { get; set; }
        public string LabName { get; set; }
        public Nullable<int> Numberofrequiredlabs { get; set; }
        public Nullable<int> Numberofavilablelabs { get; set; }
        public string Remarks { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createdon { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
