//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_college_faculty
    {
        public jntuh_college_faculty()
        {
            this.jntuh_faculty_education = new HashSet<jntuh_faculty_education>();
            this.jntuh_faculty_subjects = new HashSet<jntuh_faculty_subjects>();
        }
    
        public int id { get; set; }
        public int collegeId { get; set; }
        public string facultyFirstName { get; set; }
        public string facultyLastName { get; set; }
        public string facultySurname { get; set; }
        public int facultyTypeId { get; set; }
        public int facultyGenderId { get; set; }
        public string facultyFatherName { get; set; }
        public int facultyCategoryId { get; set; }
        public System.DateTime facultyDateOfBirth { get; set; }
        public int facultyDesignationId { get; set; }
        public string facultyOtherDesignation { get; set; }
        public int facultyDepartmentId { get; set; }
        public System.DateTime facultyDateOfAppointment { get; set; }
        public Nullable<System.DateTime> facultyDateOfResignation { get; set; }
        public bool isFacultyRatifiedByJNTU { get; set; }
        public Nullable<System.DateTime> facultyDateOfRatification { get; set; }
        public Nullable<int> facultyDurationOfRatification { get; set; }
        public Nullable<decimal> facultyPreviousExperience { get; set; }
        public decimal facultySalary { get; set; }
        public string facultyPayScale { get; set; }
        public string facultyPANNumber { get; set; }
        public string facultyAadhaarNumber { get; set; }
        public bool isRelatedToExamBranch { get; set; }
        public bool isRelatedToPlacementCell { get; set; }
        public string facultyMobile { get; set; }
        public string facultyEmail { get; set; }
        public string facultyAchievements1 { get; set; }
        public string facultyAchievements2 { get; set; }
        public string facultyAchievements3 { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public string facultyPhoto { get; set; }
        public string salaryAccountNumber { get; set; }
        public string salaryBankName { get; set; }
        public string salaryBranchName { get; set; }
        public string facultyRecruitedFor { get; set; }
        public string grossSalary { get; set; }
        public string netSalary { get; set; }
        public string FacultyRegistrationNumber { get; set; }
        public string BASStatus { get; set; }
    
        public virtual jntuh_college jntuh_college { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual jntuh_faculty_type jntuh_faculty_type { get; set; }
        public virtual jntuh_faculty_category jntuh_faculty_category { get; set; }
        public virtual jntuh_designation jntuh_designation { get; set; }
        public virtual jntuh_department jntuh_department { get; set; }
        public virtual ICollection<jntuh_faculty_education> jntuh_faculty_education { get; set; }
        public virtual ICollection<jntuh_faculty_subjects> jntuh_faculty_subjects { get; set; }
    }
}
