//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_education_category
    {
        public jntuh_education_category()
        {
            this.jntuh_faculty_education = new HashSet<jntuh_faculty_education>();
            this.jntuh_registered_faculty_education = new HashSet<jntuh_registered_faculty_education>();
            this.jntuh_registered_faculty_education_oldfaculty = new HashSet<jntuh_registered_faculty_education_oldfaculty>();
            this.jntuh_registered_faculty_education11 = new HashSet<jntuh_registered_faculty_education11>();
            this.jntuh_reinspection_registered_faculty_education = new HashSet<jntuh_reinspection_registered_faculty_education>();
        }
    
        public int id { get; set; }
        public string educationCategoryName { get; set; }
        public string educationCategoryDescription { get; set; }
        public Nullable<int> educationCategoryDisplayOrder { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual ICollection<jntuh_faculty_education> jntuh_faculty_education { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education> jntuh_registered_faculty_education { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education_oldfaculty> jntuh_registered_faculty_education_oldfaculty { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education11> jntuh_registered_faculty_education11 { get; set; }
        public virtual ICollection<jntuh_reinspection_registered_faculty_education> jntuh_reinspection_registered_faculty_education { get; set; }
    }
}
