//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_degree
    {
        public jntuh_degree()
        {
            this.jntuh_college_computer_lab_printers = new HashSet<jntuh_college_computer_lab_printers>();
            this.jntuh_college_computer_student_ratio = new HashSet<jntuh_college_computer_student_ratio>();
            this.jntuh_college_degree = new HashSet<jntuh_college_degree>();
            this.jntuh_college_faculty_student_ratio = new HashSet<jntuh_college_faculty_student_ratio>();
            this.jntuh_college_internet_bandwidth = new HashSet<jntuh_college_internet_bandwidth>();
            this.jntuh_college_legal_software = new HashSet<jntuh_college_legal_software>();
            this.jntuh_college_library_details = new HashSet<jntuh_college_library_details>();
            this.jntuh_lab_master_experments = new HashSet<jntuh_lab_master_experments>();
            this.jntuh_lab_master = new HashSet<jntuh_lab_master>();
            this.jntuh_department = new HashSet<jntuh_department>();
        }
    
        public int id { get; set; }
        public string degree { get; set; }
        public int degreeTypeId { get; set; }
        public decimal degreeDuration { get; set; }
        public string degreeDescription { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<int> degreeDisplayOrder { get; set; }
    
        public virtual ICollection<jntuh_college_computer_lab_printers> jntuh_college_computer_lab_printers { get; set; }
        public virtual ICollection<jntuh_college_computer_student_ratio> jntuh_college_computer_student_ratio { get; set; }
        public virtual ICollection<jntuh_college_degree> jntuh_college_degree { get; set; }
        public virtual ICollection<jntuh_college_faculty_student_ratio> jntuh_college_faculty_student_ratio { get; set; }
        public virtual ICollection<jntuh_college_internet_bandwidth> jntuh_college_internet_bandwidth { get; set; }
        public virtual ICollection<jntuh_college_legal_software> jntuh_college_legal_software { get; set; }
        public virtual ICollection<jntuh_college_library_details> jntuh_college_library_details { get; set; }
        public virtual ICollection<jntuh_lab_master_experments> jntuh_lab_master_experments { get; set; }
        public virtual ICollection<jntuh_lab_master> jntuh_lab_master { get; set; }
        public virtual jntuh_degree_type jntuh_degree_type { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
        public virtual ICollection<jntuh_department> jntuh_department { get; set; }
    }
}
