//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_reinspection_registered_faculty
    {
        public jntuh_reinspection_registered_faculty()
        {
            this.jntuh_reinspection_registered_faculty_education = new HashSet<jntuh_reinspection_registered_faculty_education>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public int UserId { get; set; }
        public Nullable<int> collegeId { get; set; }
        public string RegistrationNumber { get; set; }
        public string UniqueID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int GenderId { get; set; }
        public string FatherOrHusbandName { get; set; }
        public string MotherName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<bool> WorkingStatus { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string OtherDesignation { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string OtherDepartment { get; set; }
        public string grosssalary { get; set; }
        public Nullable<System.DateTime> DateOfAppointment { get; set; }
        public Nullable<bool> isFacultyRatifiedByJNTU { get; set; }
        public Nullable<System.DateTime> DateOfRatification { get; set; }
        public string ProceedingsNumber { get; set; }
        public string ProceedingDocument { get; set; }
        public string AICTEFacultyId { get; set; }
        public Nullable<int> TotalExperience { get; set; }
        public Nullable<int> TotalExperiencePresentCollege { get; set; }
        public string PANNumber { get; set; }
        public string AadhaarNumber { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string National { get; set; }
        public string InterNational { get; set; }
        public string Citation { get; set; }
        public string Awards { get; set; }
        public string Photo { get; set; }
        public string PANDocument { get; set; }
        public string AadhaarDocument { get; set; }
        public bool isActive { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public string DeactivationReason { get; set; }
        public Nullable<System.DateTime> DeactivatedOn { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public string WorkingType { get; set; }
        public string NOCFile { get; set; }
        public string PresentInstituteAssignedRole { get; set; }
        public string PresentInstituteAssignedResponsebility { get; set; }
        public string Accomplish1 { get; set; }
        public string Accomplish2 { get; set; }
        public string Accomplish3 { get; set; }
        public string Accomplish4 { get; set; }
        public string Accomplish5 { get; set; }
        public string Professional { get; set; }
        public string Professional2 { get; set; }
        public string Professiona3 { get; set; }
        public string MembershipNo1 { get; set; }
        public string MembershipNo2 { get; set; }
        public string MembershipNo3 { get; set; }
        public string MembershipCertificate1 { get; set; }
        public string MembershipCertificate2 { get; set; }
        public string MembershipCertificate3 { get; set; }
        public string AdjunctDesignation { get; set; }
        public string AdjunctDepartment { get; set; }
        public string PanVerificationStatus { get; set; }
        public string PanDeactivationReason { get; set; }
        public Nullable<bool> Absent { get; set; }
        public string ModifiedPANNumber { get; set; }
        public Nullable<bool> InvalidPANNumber { get; set; }
        public string NoRelevantUG { get; set; }
        public string NoRelevantPG { get; set; }
        public string NORelevantPHD { get; set; }
        public Nullable<bool> NoSCM { get; set; }
        public Nullable<bool> NoForm16 { get; set; }
        public Nullable<System.DateTime> ModifiedDateofAppointment { get; set; }
        public Nullable<bool> NotQualifiedAsperAICTE { get; set; }
        public Nullable<bool> MultipleRegInSameCollege { get; set; }
        public Nullable<bool> MultipleRegInDiffCollege { get; set; }
        public Nullable<bool> SamePANUsedByMultipleFaculty { get; set; }
        public Nullable<bool> PhotoCopyofPAN { get; set; }
        public Nullable<bool> AppliedPAN { get; set; }
        public Nullable<bool> LostPAN { get; set; }
        public Nullable<bool> OriginalsVerifiedUG { get; set; }
        public Nullable<bool> OriginalsVerifiedPG { get; set; }
        public Nullable<bool> OriginalsVerifiedPHD { get; set; }
        public Nullable<bool> FacultyVerificationStatus { get; set; }
        public string Others1 { get; set; }
        public string Others2 { get; set; }
        public Nullable<bool> IncompleteCertificates { get; set; }
        public string PanStatusAfterDE { get; set; }
        public string PanReasonAfterDE { get; set; }
        public Nullable<bool> NoSpecialization { get; set; }
        public Nullable<bool> FalsePAN { get; set; }
        public Nullable<bool> Notin116 { get; set; }
        public Nullable<bool> PHDundertakingnotsubmitted { get; set; }
        public Nullable<bool> Blacklistfaculy { get; set; }
        public Nullable<bool> DiscrepencyStatus { get; set; }
        public Nullable<bool> NoPhdUndertakingNew { get; set; }
    
        public virtual jntuh_department jntuh_department { get; set; }
        public virtual jntuh_designation jntuh_designation { get; set; }
        public virtual ICollection<jntuh_reinspection_registered_faculty_education> jntuh_reinspection_registered_faculty_education { get; set; }
        public virtual my_aspnet_users my_aspnet_users { get; set; }
        public virtual my_aspnet_users my_aspnet_users1 { get; set; }
    }
}
