//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_collegestatus
    {
        public int Id { get; set; }
        public int CollegeId { get; set; }
        public string CollegeCode { get; set; }
        public bool CollegeStatus { get; set; }
        public bool SIStatus { get; set; }
        public bool AICTEStatus { get; set; }
        public System.DateTime CreatedON { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
        public Nullable<int> UpDatedBy { get; set; }
    }
}
