//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jntuh_attendence_registrationnumberstracking
    {
        public int Id { get; set; }
        public string RegistrationNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string ActionType { get; set; }
        public string FacultyType { get; set; }
        public string FacultyStatus { get; set; }
        public string Reasion { get; set; }
        public System.DateTime Createdon { get; set; }
    }
}
