//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_users
    {
        public my_aspnet_users()
        {
            this.college_circulars = new HashSet<college_circulars>();
            this.college_circulars1 = new HashSet<college_circulars>();
            this.college_clusters = new HashSet<college_clusters>();
            this.college_clusters1 = new HashSet<college_clusters>();
            this.college_grade = new HashSet<college_grade>();
            this.college_grade1 = new HashSet<college_grade>();
            this.college_undertaking = new HashSet<college_undertaking>();
            this.college_undertaking1 = new HashSet<college_undertaking>();
            this.colleges_groups = new HashSet<colleges_groups>();
            this.colleges_groups1 = new HashSet<colleges_groups>();
            this.jntuh_academic_performance = new HashSet<jntuh_academic_performance>();
            this.jntuh_academic_performance1 = new HashSet<jntuh_academic_performance>();
            this.jntuh_academic_year = new HashSet<jntuh_academic_year>();
            this.jntuh_academic_year1 = new HashSet<jntuh_academic_year>();
            this.jntuh_address = new HashSet<jntuh_address>();
            this.jntuh_address1 = new HashSet<jntuh_address>();
            this.jntuh_affiliation_requests = new HashSet<jntuh_affiliation_requests>();
            this.jntuh_affiliation_requests1 = new HashSet<jntuh_affiliation_requests>();
            this.jntuh_affiliation_type = new HashSet<jntuh_affiliation_type>();
            this.jntuh_affiliation_type1 = new HashSet<jntuh_affiliation_type>();
            this.jntuh_approach_road = new HashSet<jntuh_approach_road>();
            this.jntuh_approach_road1 = new HashSet<jntuh_approach_road>();
            this.jntuh_area_requirement = new HashSet<jntuh_area_requirement>();
            this.jntuh_area_requirement1 = new HashSet<jntuh_area_requirement>();
            this.jntuh_chairperson_designation = new HashSet<jntuh_chairperson_designation>();
            this.jntuh_chairperson_designation1 = new HashSet<jntuh_chairperson_designation>();
            this.jntuh_college = new HashSet<jntuh_college>();
            this.jntuh_college1 = new HashSet<jntuh_college>();
            this.jntuh_college_academic_performance = new HashSet<jntuh_college_academic_performance>();
            this.jntuh_college_academic_performance1 = new HashSet<jntuh_college_academic_performance>();
            this.jntuh_college_academic_performance_points = new HashSet<jntuh_college_academic_performance_points>();
            this.jntuh_college_academic_performance_points1 = new HashSet<jntuh_college_academic_performance_points>();
            this.jntuh_college_affiliation = new HashSet<jntuh_college_affiliation>();
            this.jntuh_college_affiliation1 = new HashSet<jntuh_college_affiliation>();
            this.jntuh_college_affiliation_type = new HashSet<jntuh_college_affiliation_type>();
            this.jntuh_college_affiliation_type1 = new HashSet<jntuh_college_affiliation_type>();
            this.jntuh_college_antiragging_committee = new HashSet<jntuh_college_antiragging_committee>();
            this.jntuh_college_antiragging_committee1 = new HashSet<jntuh_college_antiragging_committee>();
            this.jntuh_college_antiragging_complaints = new HashSet<jntuh_college_antiragging_complaints>();
            this.jntuh_college_antiragging_complaints1 = new HashSet<jntuh_college_antiragging_complaints>();
            this.jntuh_college_area = new HashSet<jntuh_college_area>();
            this.jntuh_college_area1 = new HashSet<jntuh_college_area>();
            this.jntuh_college_chairperson = new HashSet<jntuh_college_chairperson>();
            this.jntuh_college_chairperson1 = new HashSet<jntuh_college_chairperson>();
            this.jntuh_college_closure = new HashSet<jntuh_college_closure>();
            this.jntuh_college_closure1 = new HashSet<jntuh_college_closure>();
            this.jntuh_college_committee_observations = new HashSet<jntuh_college_committee_observations>();
            this.jntuh_college_committee_observations1 = new HashSet<jntuh_college_committee_observations>();
            this.jntuh_college_computer_lab = new HashSet<jntuh_college_computer_lab>();
            this.jntuh_college_computer_lab1 = new HashSet<jntuh_college_computer_lab>();
            this.jntuh_college_computer_lab_printers = new HashSet<jntuh_college_computer_lab_printers>();
            this.jntuh_college_computer_lab_printers1 = new HashSet<jntuh_college_computer_lab_printers>();
            this.jntuh_college_computer_student_ratio = new HashSet<jntuh_college_computer_student_ratio>();
            this.jntuh_college_computer_student_ratio1 = new HashSet<jntuh_college_computer_student_ratio>();
            this.jntuh_college_degree = new HashSet<jntuh_college_degree>();
            this.jntuh_college_degree1 = new HashSet<jntuh_college_degree>();
            this.jntuh_college_desirable_others = new HashSet<jntuh_college_desirable_others>();
            this.jntuh_college_desirable_others1 = new HashSet<jntuh_college_desirable_others>();
            this.jntuh_college_desirable_requirement = new HashSet<jntuh_college_desirable_requirement>();
            this.jntuh_college_desirable_requirement1 = new HashSet<jntuh_college_desirable_requirement>();
            this.jntuh_college_document = new HashSet<jntuh_college_document>();
            this.jntuh_college_document1 = new HashSet<jntuh_college_document>();
            this.jntuh_college_edit_remarks = new HashSet<jntuh_college_edit_remarks>();
            this.jntuh_college_edit_remarks1 = new HashSet<jntuh_college_edit_remarks>();
            this.jntuh_college_edit_status = new HashSet<jntuh_college_edit_status>();
            this.jntuh_college_edit_status1 = new HashSet<jntuh_college_edit_status>();
            this.jntuh_college_edit_status_log = new HashSet<jntuh_college_edit_status_log>();
            this.jntuh_college_edit_status_log1 = new HashSet<jntuh_college_edit_status_log>();
            this.jntuh_college_enclosures = new HashSet<jntuh_college_enclosures>();
            this.jntuh_college_enclosures1 = new HashSet<jntuh_college_enclosures>();
            this.jntuh_college_enclosures_hardcopy = new HashSet<jntuh_college_enclosures_hardcopy>();
            this.jntuh_college_enclosures_hardcopy1 = new HashSet<jntuh_college_enclosures_hardcopy>();
            this.jntuh_college_establishment = new HashSet<jntuh_college_establishment>();
            this.jntuh_college_establishment1 = new HashSet<jntuh_college_establishment>();
            this.jntuh_college_examination_branch = new HashSet<jntuh_college_examination_branch>();
            this.jntuh_college_examination_branch1 = new HashSet<jntuh_college_examination_branch>();
            this.jntuh_college_examination_branch_edep = new HashSet<jntuh_college_examination_branch_edep>();
            this.jntuh_college_examination_branch_edep1 = new HashSet<jntuh_college_examination_branch_edep>();
            this.jntuh_college_examination_branch_security = new HashSet<jntuh_college_examination_branch_security>();
            this.jntuh_college_examination_branch_security1 = new HashSet<jntuh_college_examination_branch_security>();
            this.jntuh_college_examination_branch_staff = new HashSet<jntuh_college_examination_branch_staff>();
            this.jntuh_college_examination_branch_staff1 = new HashSet<jntuh_college_examination_branch_staff>();
            this.jntuh_college_expenditure = new HashSet<jntuh_college_expenditure>();
            this.jntuh_college_expenditure1 = new HashSet<jntuh_college_expenditure>();
            this.jntuh_college_expenditure_type = new HashSet<jntuh_college_expenditure_type>();
            this.jntuh_college_expenditure_type1 = new HashSet<jntuh_college_expenditure_type>();
            this.jntuh_college_faculty = new HashSet<jntuh_college_faculty>();
            this.jntuh_college_faculty1 = new HashSet<jntuh_college_faculty>();
            this.jntuh_college_faculty_deficiency = new HashSet<jntuh_college_faculty_deficiency>();
            this.jntuh_college_faculty_registered = new HashSet<jntuh_college_faculty_registered>();
            this.jntuh_college_faculty_registered1 = new HashSet<jntuh_college_faculty_registered>();
            this.jntuh_college_faculty_student_ratio = new HashSet<jntuh_college_faculty_student_ratio>();
            this.jntuh_college_faculty_student_ratio1 = new HashSet<jntuh_college_faculty_student_ratio>();
            this.jntuh_college_faculty_verified = new HashSet<jntuh_college_faculty_verified>();
            this.jntuh_college_fee_reimbursement = new HashSet<jntuh_college_fee_reimbursement>();
            this.jntuh_college_fee_reimbursement1 = new HashSet<jntuh_college_fee_reimbursement>();
            this.jntuh_college_ffc_overall_faculty_studentratio = new HashSet<jntuh_college_ffc_overall_faculty_studentratio>();
            this.jntuh_college_ffc_overall_faculty_studentratio1 = new HashSet<jntuh_college_ffc_overall_faculty_studentratio>();
            this.jntuh_college_funds = new HashSet<jntuh_college_funds>();
            this.jntuh_college_funds1 = new HashSet<jntuh_college_funds>();
            this.jntuh_college_grievance_committee = new HashSet<jntuh_college_grievance_committee>();
            this.jntuh_college_grievance_committee1 = new HashSet<jntuh_college_grievance_committee>();
            this.jntuh_college_grievance_complaints = new HashSet<jntuh_college_grievance_complaints>();
            this.jntuh_college_grievance_complaints1 = new HashSet<jntuh_college_grievance_complaints>();
            this.jntuh_college_hostel_maintenance = new HashSet<jntuh_college_hostel_maintenance>();
            this.jntuh_college_hostel_maintenance1 = new HashSet<jntuh_college_hostel_maintenance>();
            this.jntuh_college_income = new HashSet<jntuh_college_income>();
            this.jntuh_college_income1 = new HashSet<jntuh_college_income>();
            this.jntuh_college_income_type = new HashSet<jntuh_college_income_type>();
            this.jntuh_college_income_type1 = new HashSet<jntuh_college_income_type>();
            this.jntuh_college_infrastructure_parameters = new HashSet<jntuh_college_infrastructure_parameters>();
            this.jntuh_college_infrastructure_parameters1 = new HashSet<jntuh_college_infrastructure_parameters>();
            this.jntuh_college_intake_existing = new HashSet<jntuh_college_intake_existing>();
            this.jntuh_college_intake_existing1 = new HashSet<jntuh_college_intake_existing>();
            this.jntuh_college_intake_existing_datentry2 = new HashSet<jntuh_college_intake_existing_datentry2>();
            this.jntuh_college_intake_existing_datentry21 = new HashSet<jntuh_college_intake_existing_datentry2>();
            this.jntuh_college_intake_proposed = new HashSet<jntuh_college_intake_proposed>();
            this.jntuh_college_intake_proposed1 = new HashSet<jntuh_college_intake_proposed>();
            this.jntuh_college_internet_bandwidth = new HashSet<jntuh_college_internet_bandwidth>();
            this.jntuh_college_internet_bandwidth1 = new HashSet<jntuh_college_internet_bandwidth>();
            this.jntuh_college_lab = new HashSet<jntuh_college_lab>();
            this.jntuh_college_lab1 = new HashSet<jntuh_college_lab>();
            this.jntuh_college_laboratories_deficiency = new HashSet<jntuh_college_laboratories_deficiency>();
            this.jntuh_college_land = new HashSet<jntuh_college_land>();
            this.jntuh_college_land1 = new HashSet<jntuh_college_land>();
            this.jntuh_college_land_registration = new HashSet<jntuh_college_land_registration>();
            this.jntuh_college_land_registration1 = new HashSet<jntuh_college_land_registration>();
            this.jntuh_college_legal_software = new HashSet<jntuh_college_legal_software>();
            this.jntuh_college_legal_software1 = new HashSet<jntuh_college_legal_software>();
            this.jntuh_college_library = new HashSet<jntuh_college_library>();
            this.jntuh_college_library1 = new HashSet<jntuh_college_library>();
            this.jntuh_college_library_details = new HashSet<jntuh_college_library_details>();
            this.jntuh_college_library_details1 = new HashSet<jntuh_college_library_details>();
            this.jntuh_college_miscellaneous_parameters = new HashSet<jntuh_college_miscellaneous_parameters>();
            this.jntuh_college_miscellaneous_parameters1 = new HashSet<jntuh_college_miscellaneous_parameters>();
            this.jntuh_college_name_change = new HashSet<jntuh_college_name_change>();
            this.jntuh_college_name_change1 = new HashSet<jntuh_college_name_change>();
            this.jntuh_college_news = new HashSet<jntuh_college_news>();
            this.jntuh_college_news1 = new HashSet<jntuh_college_news>();
            this.jntuh_college_news_old = new HashSet<jntuh_college_news_old>();
            this.jntuh_college_news_old1 = new HashSet<jntuh_college_news_old>();
            this.jntuh_college_other_university_courses = new HashSet<jntuh_college_other_university_courses>();
            this.jntuh_college_other_university_courses1 = new HashSet<jntuh_college_other_university_courses>();
            this.jntuh_college_overall_faculty_studentratio = new HashSet<jntuh_college_overall_faculty_studentratio>();
            this.jntuh_college_overall_faculty_studentratio1 = new HashSet<jntuh_college_overall_faculty_studentratio>();
            this.jntuh_college_payment = new HashSet<jntuh_college_payment>();
            this.jntuh_college_payment1 = new HashSet<jntuh_college_payment>();
            this.jntuh_college_paymentoffee = new HashSet<jntuh_college_paymentoffee>();
            this.jntuh_college_paymentoffee1 = new HashSet<jntuh_college_paymentoffee>();
            this.jntuh_college_paymentoffee_type = new HashSet<jntuh_college_paymentoffee_type>();
            this.jntuh_college_paymentoffee_type1 = new HashSet<jntuh_college_paymentoffee_type>();
            this.jntuh_college_pgcourse_faculty = new HashSet<jntuh_college_pgcourse_faculty>();
            this.jntuh_college_pgcourse_faculty1 = new HashSet<jntuh_college_pgcourse_faculty>();
            this.jntuh_college_pgcourses = new HashSet<jntuh_college_pgcourses>();
            this.jntuh_college_pgcourses1 = new HashSet<jntuh_college_pgcourses>();
            this.jntuh_college_placement = new HashSet<jntuh_college_placement>();
            this.jntuh_college_placement1 = new HashSet<jntuh_college_placement>();
            this.jntuh_college_principal_director = new HashSet<jntuh_college_principal_director>();
            this.jntuh_college_principal_director1 = new HashSet<jntuh_college_principal_director>();
            this.jntuh_college_principal_ratified = new HashSet<jntuh_college_principal_ratified>();
            this.jntuh_college_principal_ratified1 = new HashSet<jntuh_college_principal_ratified>();
            this.jntuh_college_principal_registered = new HashSet<jntuh_college_principal_registered>();
            this.jntuh_college_principal_registered1 = new HashSet<jntuh_college_principal_registered>();
            this.jntuh_college_rti_complaints = new HashSet<jntuh_college_rti_complaints>();
            this.jntuh_college_rti_complaints1 = new HashSet<jntuh_college_rti_complaints>();
            this.jntuh_college_rti_details = new HashSet<jntuh_college_rti_details>();
            this.jntuh_college_rti_details1 = new HashSet<jntuh_college_rti_details>();
            this.jntuh_college_sports = new HashSet<jntuh_college_sports>();
            this.jntuh_college_sports1 = new HashSet<jntuh_college_sports>();
            this.jntuh_college_staticdata_modifications = new HashSet<jntuh_college_staticdata_modifications>();
            this.jntuh_college_staticdata_modifications1 = new HashSet<jntuh_college_staticdata_modifications>();
            this.jntuh_college_status = new HashSet<jntuh_college_status>();
            this.jntuh_college_status1 = new HashSet<jntuh_college_status>();
            this.jntuh_college_teaching_faculty_position = new HashSet<jntuh_college_teaching_faculty_position>();
            this.jntuh_college_teaching_faculty_position1 = new HashSet<jntuh_college_teaching_faculty_position>();
            this.jntuh_college_terms_accepted = new HashSet<jntuh_college_terms_accepted>();
            this.jntuh_college_terms_accepted1 = new HashSet<jntuh_college_terms_accepted>();
            this.jntuh_college_type = new HashSet<jntuh_college_type>();
            this.jntuh_college_type1 = new HashSet<jntuh_college_type>();
            this.jntuh_college_users = new HashSet<jntuh_college_users>();
            this.jntuh_college_users1 = new HashSet<jntuh_college_users>();
            this.jntuh_college_users2 = new HashSet<jntuh_college_users>();
            this.jntuh_college_women_protection_cell = new HashSet<jntuh_college_women_protection_cell>();
            this.jntuh_college_women_protection_cell1 = new HashSet<jntuh_college_women_protection_cell>();
            this.jntuh_college_women_protection_cell_complaints = new HashSet<jntuh_college_women_protection_cell_complaints>();
            this.jntuh_college_women_protection_cell_complaints1 = new HashSet<jntuh_college_women_protection_cell_complaints>();
            this.jntuh_committee_observations = new HashSet<jntuh_committee_observations>();
            this.jntuh_committee_observations1 = new HashSet<jntuh_committee_observations>();
            this.jntuh_committee_submission = new HashSet<jntuh_committee_submission>();
            this.jntuh_computer_student_ratio_norms = new HashSet<jntuh_computer_student_ratio_norms>();
            this.jntuh_computer_student_ratio_norms1 = new HashSet<jntuh_computer_student_ratio_norms>();
            this.jntuh_course_affiliation_status = new HashSet<jntuh_course_affiliation_status>();
            this.jntuh_course_affiliation_status1 = new HashSet<jntuh_course_affiliation_status>();
            this.jntuh_dataentry_allotment = new HashSet<jntuh_dataentry_allotment>();
            this.jntuh_dataentry_allotment1 = new HashSet<jntuh_dataentry_allotment>();
            this.jntuh_dataentry_allotment2 = new HashSet<jntuh_dataentry_allotment>();
            this.jntuh_degree = new HashSet<jntuh_degree>();
            this.jntuh_degree1 = new HashSet<jntuh_degree>();
            this.jntuh_degree_type = new HashSet<jntuh_degree_type>();
            this.jntuh_degree_type1 = new HashSet<jntuh_degree_type>();
            this.jntuh_department = new HashSet<jntuh_department>();
            this.jntuh_department1 = new HashSet<jntuh_department>();
            this.jntuh_designation = new HashSet<jntuh_designation>();
            this.jntuh_designation1 = new HashSet<jntuh_designation>();
            this.jntuh_desirable_requirement_type = new HashSet<jntuh_desirable_requirement_type>();
            this.jntuh_desirable_requirement_type1 = new HashSet<jntuh_desirable_requirement_type>();
            this.jntuh_district = new HashSet<jntuh_district>();
            this.jntuh_district1 = new HashSet<jntuh_district>();
            this.jntuh_documents_required = new HashSet<jntuh_documents_required>();
            this.jntuh_documents_required1 = new HashSet<jntuh_documents_required>();
            this.jntuh_download = new HashSet<jntuh_download>();
            this.jntuh_download1 = new HashSet<jntuh_download>();
            this.jntuh_edep_equipment = new HashSet<jntuh_edep_equipment>();
            this.jntuh_edep_equipment1 = new HashSet<jntuh_edep_equipment>();
            this.jntuh_education_category = new HashSet<jntuh_education_category>();
            this.jntuh_education_category1 = new HashSet<jntuh_education_category>();
            this.jntuh_enclosures = new HashSet<jntuh_enclosures>();
            this.jntuh_enclosures1 = new HashSet<jntuh_enclosures>();
            this.jntuh_error_log = new HashSet<jntuh_error_log>();
            this.jntuh_error_log1 = new HashSet<jntuh_error_log>();
            this.jntuh_facility_status = new HashSet<jntuh_facility_status>();
            this.jntuh_facility_status1 = new HashSet<jntuh_facility_status>();
            this.jntuh_faculty_category = new HashSet<jntuh_faculty_category>();
            this.jntuh_faculty_category1 = new HashSet<jntuh_faculty_category>();
            this.jntuh_faculty_education = new HashSet<jntuh_faculty_education>();
            this.jntuh_faculty_education1 = new HashSet<jntuh_faculty_education>();
            this.jntuh_faculty_student_ratio_norms = new HashSet<jntuh_faculty_student_ratio_norms>();
            this.jntuh_faculty_student_ratio_norms1 = new HashSet<jntuh_faculty_student_ratio_norms>();
            this.jntuh_faculty_subjects = new HashSet<jntuh_faculty_subjects>();
            this.jntuh_faculty_subjects1 = new HashSet<jntuh_faculty_subjects>();
            this.jntuh_faculty_type = new HashSet<jntuh_faculty_type>();
            this.jntuh_faculty_type1 = new HashSet<jntuh_faculty_type>();
            this.jntuh_ffc_cluster_emails = new HashSet<jntuh_ffc_cluster_emails>();
            this.jntuh_ffc_external_auditor_groups = new HashSet<jntuh_ffc_external_auditor_groups>();
            this.jntuh_ffc_external_auditor_groups1 = new HashSet<jntuh_ffc_external_auditor_groups>();
            this.jntuh_grc_designation = new HashSet<jntuh_grc_designation>();
            this.jntuh_grc_designation1 = new HashSet<jntuh_grc_designation>();
            this.jntuh_infrastructure_parameters = new HashSet<jntuh_infrastructure_parameters>();
            this.jntuh_infrastructure_parameters1 = new HashSet<jntuh_infrastructure_parameters>();
            this.jntuh_inspection_phase = new HashSet<jntuh_inspection_phase>();
            this.jntuh_inspection_phase1 = new HashSet<jntuh_inspection_phase>();
            this.jntuh_internet_bandwidth_norms = new HashSet<jntuh_internet_bandwidth_norms>();
            this.jntuh_internet_bandwidth_norms1 = new HashSet<jntuh_internet_bandwidth_norms>();
            this.jntuh_land_category = new HashSet<jntuh_land_category>();
            this.jntuh_land_category1 = new HashSet<jntuh_land_category>();
            this.jntuh_land_registration_type = new HashSet<jntuh_land_registration_type>();
            this.jntuh_land_registration_type1 = new HashSet<jntuh_land_registration_type>();
            this.jntuh_land_type = new HashSet<jntuh_land_type>();
            this.jntuh_land_type1 = new HashSet<jntuh_land_type>();
            this.jntuh_menu = new HashSet<jntuh_menu>();
            this.jntuh_menu1 = new HashSet<jntuh_menu>();
            this.jntuh_miscellaneous_parameters = new HashSet<jntuh_miscellaneous_parameters>();
            this.jntuh_miscellaneous_parameters1 = new HashSet<jntuh_miscellaneous_parameters>();
            this.jntuh_newsevents = new HashSet<jntuh_newsevents>();
            this.jntuh_newsevents1 = new HashSet<jntuh_newsevents>();
            this.jntuh_other_information_type = new HashSet<jntuh_other_information_type>();
            this.jntuh_other_information_type1 = new HashSet<jntuh_other_information_type>();
            this.jntuh_payment_mode = new HashSet<jntuh_payment_mode>();
            this.jntuh_payment_mode1 = new HashSet<jntuh_payment_mode>();
            this.jntuh_phd_subject = new HashSet<jntuh_phd_subject>();
            this.jntuh_phd_subject1 = new HashSet<jntuh_phd_subject>();
            this.jntuh_printers_norms = new HashSet<jntuh_printers_norms>();
            this.jntuh_printers_norms1 = new HashSet<jntuh_printers_norms>();
            this.jntuh_program_type = new HashSet<jntuh_program_type>();
            this.jntuh_program_type1 = new HashSet<jntuh_program_type>();
            this.jntuh_qualification = new HashSet<jntuh_qualification>();
            this.jntuh_qualification1 = new HashSet<jntuh_qualification>();
            this.jntuh_registered_faculty = new HashSet<jntuh_registered_faculty>();
            this.jntuh_registered_faculty1 = new HashSet<jntuh_registered_faculty>();
            this.jntuh_registered_faculty_education = new HashSet<jntuh_registered_faculty_education>();
            this.jntuh_registered_faculty_education1 = new HashSet<jntuh_registered_faculty_education>();
            this.jntuh_registered_faculty_education_oldfaculty = new HashSet<jntuh_registered_faculty_education_oldfaculty>();
            this.jntuh_registered_faculty_education_oldfaculty1 = new HashSet<jntuh_registered_faculty_education_oldfaculty>();
            this.jntuh_registered_faculty_education11 = new HashSet<jntuh_registered_faculty_education11>();
            this.jntuh_registered_faculty_education111 = new HashSet<jntuh_registered_faculty_education11>();
            this.jntuh_registered_faculty_experience = new HashSet<jntuh_registered_faculty_experience>();
            this.jntuh_registered_faculty_experience1 = new HashSet<jntuh_registered_faculty_experience>();
            this.jntuh_registered_faculty_experience_log = new HashSet<jntuh_registered_faculty_experience_log>();
            this.jntuh_registered_faculty_experience_log1 = new HashSet<jntuh_registered_faculty_experience_log>();
            this.jntuh_registered_faculty_oldfaculty = new HashSet<jntuh_registered_faculty_oldfaculty>();
            this.jntuh_registered_faculty_oldfaculty1 = new HashSet<jntuh_registered_faculty_oldfaculty>();
            this.jntuh_reinspection_college_laboratories_deficiency = new HashSet<jntuh_reinspection_college_laboratories_deficiency>();
            this.jntuh_reinspection_registered_faculty = new HashSet<jntuh_reinspection_registered_faculty>();
            this.jntuh_reinspection_registered_faculty1 = new HashSet<jntuh_reinspection_registered_faculty>();
            this.jntuh_reinspection_registered_faculty_education = new HashSet<jntuh_reinspection_registered_faculty_education>();
            this.jntuh_reinspection_registered_faculty_education1 = new HashSet<jntuh_reinspection_registered_faculty_education>();
            this.jntuh_shift = new HashSet<jntuh_shift>();
            this.jntuh_shift1 = new HashSet<jntuh_shift>();
            this.jntuh_society_other_colleges = new HashSet<jntuh_society_other_colleges>();
            this.jntuh_society_other_colleges1 = new HashSet<jntuh_society_other_colleges>();
            this.jntuh_society_other_locations_colleges = new HashSet<jntuh_society_other_locations_colleges>();
            this.jntuh_society_other_locations_colleges1 = new HashSet<jntuh_society_other_locations_colleges>();
            this.jntuh_software_norms = new HashSet<jntuh_software_norms>();
            this.jntuh_software_norms1 = new HashSet<jntuh_software_norms>();
            this.jntuh_specialization = new HashSet<jntuh_specialization>();
            this.jntuh_specialization1 = new HashSet<jntuh_specialization>();
            this.jntuh_sports_type = new HashSet<jntuh_sports_type>();
            this.jntuh_sports_type1 = new HashSet<jntuh_sports_type>();
            this.jntuh_stackholder_type = new HashSet<jntuh_stackholder_type>();
            this.jntuh_stackholder_type1 = new HashSet<jntuh_stackholder_type>();
            this.jntuh_state = new HashSet<jntuh_state>();
            this.jntuh_state1 = new HashSet<jntuh_state>();
            this.jntuh_transport_type = new HashSet<jntuh_transport_type>();
            this.jntuh_transport_type1 = new HashSet<jntuh_transport_type>();
            this.jntuh_university = new HashSet<jntuh_university>();
            this.jntuh_university1 = new HashSet<jntuh_university>();
            this.jntuh_water_type = new HashSet<jntuh_water_type>();
            this.jntuh_water_type1 = new HashSet<jntuh_water_type>();
            this.jntuh_year_in_degree = new HashSet<jntuh_year_in_degree>();
            this.jntuh_year_in_degree1 = new HashSet<jntuh_year_in_degree>();
            this.my_aspnet_usersinroles = new HashSet<my_aspnet_usersinroles>();
        }
    
        public int id { get; set; }
        public int applicationId { get; set; }
        public string name { get; set; }
        public bool isAnonymous { get; set; }
        public Nullable<System.DateTime> lastActivityDate { get; set; }
    
        public virtual ICollection<college_circulars> college_circulars { get; set; }
        public virtual ICollection<college_circulars> college_circulars1 { get; set; }
        public virtual ICollection<college_clusters> college_clusters { get; set; }
        public virtual ICollection<college_clusters> college_clusters1 { get; set; }
        public virtual ICollection<college_grade> college_grade { get; set; }
        public virtual ICollection<college_grade> college_grade1 { get; set; }
        public virtual ICollection<college_undertaking> college_undertaking { get; set; }
        public virtual ICollection<college_undertaking> college_undertaking1 { get; set; }
        public virtual ICollection<colleges_groups> colleges_groups { get; set; }
        public virtual ICollection<colleges_groups> colleges_groups1 { get; set; }
        public virtual ICollection<jntuh_academic_performance> jntuh_academic_performance { get; set; }
        public virtual ICollection<jntuh_academic_performance> jntuh_academic_performance1 { get; set; }
        public virtual ICollection<jntuh_academic_year> jntuh_academic_year { get; set; }
        public virtual ICollection<jntuh_academic_year> jntuh_academic_year1 { get; set; }
        public virtual ICollection<jntuh_address> jntuh_address { get; set; }
        public virtual ICollection<jntuh_address> jntuh_address1 { get; set; }
        public virtual ICollection<jntuh_affiliation_requests> jntuh_affiliation_requests { get; set; }
        public virtual ICollection<jntuh_affiliation_requests> jntuh_affiliation_requests1 { get; set; }
        public virtual ICollection<jntuh_affiliation_type> jntuh_affiliation_type { get; set; }
        public virtual ICollection<jntuh_affiliation_type> jntuh_affiliation_type1 { get; set; }
        public virtual ICollection<jntuh_approach_road> jntuh_approach_road { get; set; }
        public virtual ICollection<jntuh_approach_road> jntuh_approach_road1 { get; set; }
        public virtual ICollection<jntuh_area_requirement> jntuh_area_requirement { get; set; }
        public virtual ICollection<jntuh_area_requirement> jntuh_area_requirement1 { get; set; }
        public virtual ICollection<jntuh_chairperson_designation> jntuh_chairperson_designation { get; set; }
        public virtual ICollection<jntuh_chairperson_designation> jntuh_chairperson_designation1 { get; set; }
        public virtual ICollection<jntuh_college> jntuh_college { get; set; }
        public virtual ICollection<jntuh_college> jntuh_college1 { get; set; }
        public virtual ICollection<jntuh_college_academic_performance> jntuh_college_academic_performance { get; set; }
        public virtual ICollection<jntuh_college_academic_performance> jntuh_college_academic_performance1 { get; set; }
        public virtual ICollection<jntuh_college_academic_performance_points> jntuh_college_academic_performance_points { get; set; }
        public virtual ICollection<jntuh_college_academic_performance_points> jntuh_college_academic_performance_points1 { get; set; }
        public virtual ICollection<jntuh_college_affiliation> jntuh_college_affiliation { get; set; }
        public virtual ICollection<jntuh_college_affiliation> jntuh_college_affiliation1 { get; set; }
        public virtual ICollection<jntuh_college_affiliation_type> jntuh_college_affiliation_type { get; set; }
        public virtual ICollection<jntuh_college_affiliation_type> jntuh_college_affiliation_type1 { get; set; }
        public virtual ICollection<jntuh_college_antiragging_committee> jntuh_college_antiragging_committee { get; set; }
        public virtual ICollection<jntuh_college_antiragging_committee> jntuh_college_antiragging_committee1 { get; set; }
        public virtual ICollection<jntuh_college_antiragging_complaints> jntuh_college_antiragging_complaints { get; set; }
        public virtual ICollection<jntuh_college_antiragging_complaints> jntuh_college_antiragging_complaints1 { get; set; }
        public virtual ICollection<jntuh_college_area> jntuh_college_area { get; set; }
        public virtual ICollection<jntuh_college_area> jntuh_college_area1 { get; set; }
        public virtual ICollection<jntuh_college_chairperson> jntuh_college_chairperson { get; set; }
        public virtual ICollection<jntuh_college_chairperson> jntuh_college_chairperson1 { get; set; }
        public virtual ICollection<jntuh_college_closure> jntuh_college_closure { get; set; }
        public virtual ICollection<jntuh_college_closure> jntuh_college_closure1 { get; set; }
        public virtual ICollection<jntuh_college_committee_observations> jntuh_college_committee_observations { get; set; }
        public virtual ICollection<jntuh_college_committee_observations> jntuh_college_committee_observations1 { get; set; }
        public virtual ICollection<jntuh_college_computer_lab> jntuh_college_computer_lab { get; set; }
        public virtual ICollection<jntuh_college_computer_lab> jntuh_college_computer_lab1 { get; set; }
        public virtual ICollection<jntuh_college_computer_lab_printers> jntuh_college_computer_lab_printers { get; set; }
        public virtual ICollection<jntuh_college_computer_lab_printers> jntuh_college_computer_lab_printers1 { get; set; }
        public virtual ICollection<jntuh_college_computer_student_ratio> jntuh_college_computer_student_ratio { get; set; }
        public virtual ICollection<jntuh_college_computer_student_ratio> jntuh_college_computer_student_ratio1 { get; set; }
        public virtual ICollection<jntuh_college_degree> jntuh_college_degree { get; set; }
        public virtual ICollection<jntuh_college_degree> jntuh_college_degree1 { get; set; }
        public virtual ICollection<jntuh_college_desirable_others> jntuh_college_desirable_others { get; set; }
        public virtual ICollection<jntuh_college_desirable_others> jntuh_college_desirable_others1 { get; set; }
        public virtual ICollection<jntuh_college_desirable_requirement> jntuh_college_desirable_requirement { get; set; }
        public virtual ICollection<jntuh_college_desirable_requirement> jntuh_college_desirable_requirement1 { get; set; }
        public virtual ICollection<jntuh_college_document> jntuh_college_document { get; set; }
        public virtual ICollection<jntuh_college_document> jntuh_college_document1 { get; set; }
        public virtual ICollection<jntuh_college_edit_remarks> jntuh_college_edit_remarks { get; set; }
        public virtual ICollection<jntuh_college_edit_remarks> jntuh_college_edit_remarks1 { get; set; }
        public virtual ICollection<jntuh_college_edit_status> jntuh_college_edit_status { get; set; }
        public virtual ICollection<jntuh_college_edit_status> jntuh_college_edit_status1 { get; set; }
        public virtual ICollection<jntuh_college_edit_status_log> jntuh_college_edit_status_log { get; set; }
        public virtual ICollection<jntuh_college_edit_status_log> jntuh_college_edit_status_log1 { get; set; }
        public virtual ICollection<jntuh_college_enclosures> jntuh_college_enclosures { get; set; }
        public virtual ICollection<jntuh_college_enclosures> jntuh_college_enclosures1 { get; set; }
        public virtual ICollection<jntuh_college_enclosures_hardcopy> jntuh_college_enclosures_hardcopy { get; set; }
        public virtual ICollection<jntuh_college_enclosures_hardcopy> jntuh_college_enclosures_hardcopy1 { get; set; }
        public virtual ICollection<jntuh_college_establishment> jntuh_college_establishment { get; set; }
        public virtual ICollection<jntuh_college_establishment> jntuh_college_establishment1 { get; set; }
        public virtual ICollection<jntuh_college_examination_branch> jntuh_college_examination_branch { get; set; }
        public virtual ICollection<jntuh_college_examination_branch> jntuh_college_examination_branch1 { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_edep> jntuh_college_examination_branch_edep { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_edep> jntuh_college_examination_branch_edep1 { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_security> jntuh_college_examination_branch_security { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_security> jntuh_college_examination_branch_security1 { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_staff> jntuh_college_examination_branch_staff { get; set; }
        public virtual ICollection<jntuh_college_examination_branch_staff> jntuh_college_examination_branch_staff1 { get; set; }
        public virtual ICollection<jntuh_college_expenditure> jntuh_college_expenditure { get; set; }
        public virtual ICollection<jntuh_college_expenditure> jntuh_college_expenditure1 { get; set; }
        public virtual ICollection<jntuh_college_expenditure_type> jntuh_college_expenditure_type { get; set; }
        public virtual ICollection<jntuh_college_expenditure_type> jntuh_college_expenditure_type1 { get; set; }
        public virtual ICollection<jntuh_college_faculty> jntuh_college_faculty { get; set; }
        public virtual ICollection<jntuh_college_faculty> jntuh_college_faculty1 { get; set; }
        public virtual ICollection<jntuh_college_faculty_deficiency> jntuh_college_faculty_deficiency { get; set; }
        public virtual ICollection<jntuh_college_faculty_registered> jntuh_college_faculty_registered { get; set; }
        public virtual ICollection<jntuh_college_faculty_registered> jntuh_college_faculty_registered1 { get; set; }
        public virtual ICollection<jntuh_college_faculty_student_ratio> jntuh_college_faculty_student_ratio { get; set; }
        public virtual ICollection<jntuh_college_faculty_student_ratio> jntuh_college_faculty_student_ratio1 { get; set; }
        public virtual ICollection<jntuh_college_faculty_verified> jntuh_college_faculty_verified { get; set; }
        public virtual ICollection<jntuh_college_fee_reimbursement> jntuh_college_fee_reimbursement { get; set; }
        public virtual ICollection<jntuh_college_fee_reimbursement> jntuh_college_fee_reimbursement1 { get; set; }
        public virtual ICollection<jntuh_college_ffc_overall_faculty_studentratio> jntuh_college_ffc_overall_faculty_studentratio { get; set; }
        public virtual ICollection<jntuh_college_ffc_overall_faculty_studentratio> jntuh_college_ffc_overall_faculty_studentratio1 { get; set; }
        public virtual ICollection<jntuh_college_funds> jntuh_college_funds { get; set; }
        public virtual ICollection<jntuh_college_funds> jntuh_college_funds1 { get; set; }
        public virtual ICollection<jntuh_college_grievance_committee> jntuh_college_grievance_committee { get; set; }
        public virtual ICollection<jntuh_college_grievance_committee> jntuh_college_grievance_committee1 { get; set; }
        public virtual ICollection<jntuh_college_grievance_complaints> jntuh_college_grievance_complaints { get; set; }
        public virtual ICollection<jntuh_college_grievance_complaints> jntuh_college_grievance_complaints1 { get; set; }
        public virtual ICollection<jntuh_college_hostel_maintenance> jntuh_college_hostel_maintenance { get; set; }
        public virtual ICollection<jntuh_college_hostel_maintenance> jntuh_college_hostel_maintenance1 { get; set; }
        public virtual ICollection<jntuh_college_income> jntuh_college_income { get; set; }
        public virtual ICollection<jntuh_college_income> jntuh_college_income1 { get; set; }
        public virtual ICollection<jntuh_college_income_type> jntuh_college_income_type { get; set; }
        public virtual ICollection<jntuh_college_income_type> jntuh_college_income_type1 { get; set; }
        public virtual ICollection<jntuh_college_infrastructure_parameters> jntuh_college_infrastructure_parameters { get; set; }
        public virtual ICollection<jntuh_college_infrastructure_parameters> jntuh_college_infrastructure_parameters1 { get; set; }
        public virtual ICollection<jntuh_college_intake_existing> jntuh_college_intake_existing { get; set; }
        public virtual ICollection<jntuh_college_intake_existing> jntuh_college_intake_existing1 { get; set; }
        public virtual ICollection<jntuh_college_intake_existing_datentry2> jntuh_college_intake_existing_datentry2 { get; set; }
        public virtual ICollection<jntuh_college_intake_existing_datentry2> jntuh_college_intake_existing_datentry21 { get; set; }
        public virtual ICollection<jntuh_college_intake_proposed> jntuh_college_intake_proposed { get; set; }
        public virtual ICollection<jntuh_college_intake_proposed> jntuh_college_intake_proposed1 { get; set; }
        public virtual ICollection<jntuh_college_internet_bandwidth> jntuh_college_internet_bandwidth { get; set; }
        public virtual ICollection<jntuh_college_internet_bandwidth> jntuh_college_internet_bandwidth1 { get; set; }
        public virtual ICollection<jntuh_college_lab> jntuh_college_lab { get; set; }
        public virtual ICollection<jntuh_college_lab> jntuh_college_lab1 { get; set; }
        public virtual ICollection<jntuh_college_laboratories_deficiency> jntuh_college_laboratories_deficiency { get; set; }
        public virtual ICollection<jntuh_college_land> jntuh_college_land { get; set; }
        public virtual ICollection<jntuh_college_land> jntuh_college_land1 { get; set; }
        public virtual ICollection<jntuh_college_land_registration> jntuh_college_land_registration { get; set; }
        public virtual ICollection<jntuh_college_land_registration> jntuh_college_land_registration1 { get; set; }
        public virtual ICollection<jntuh_college_legal_software> jntuh_college_legal_software { get; set; }
        public virtual ICollection<jntuh_college_legal_software> jntuh_college_legal_software1 { get; set; }
        public virtual ICollection<jntuh_college_library> jntuh_college_library { get; set; }
        public virtual ICollection<jntuh_college_library> jntuh_college_library1 { get; set; }
        public virtual ICollection<jntuh_college_library_details> jntuh_college_library_details { get; set; }
        public virtual ICollection<jntuh_college_library_details> jntuh_college_library_details1 { get; set; }
        public virtual ICollection<jntuh_college_miscellaneous_parameters> jntuh_college_miscellaneous_parameters { get; set; }
        public virtual ICollection<jntuh_college_miscellaneous_parameters> jntuh_college_miscellaneous_parameters1 { get; set; }
        public virtual ICollection<jntuh_college_name_change> jntuh_college_name_change { get; set; }
        public virtual ICollection<jntuh_college_name_change> jntuh_college_name_change1 { get; set; }
        public virtual ICollection<jntuh_college_news> jntuh_college_news { get; set; }
        public virtual ICollection<jntuh_college_news> jntuh_college_news1 { get; set; }
        public virtual ICollection<jntuh_college_news_old> jntuh_college_news_old { get; set; }
        public virtual ICollection<jntuh_college_news_old> jntuh_college_news_old1 { get; set; }
        public virtual ICollection<jntuh_college_other_university_courses> jntuh_college_other_university_courses { get; set; }
        public virtual ICollection<jntuh_college_other_university_courses> jntuh_college_other_university_courses1 { get; set; }
        public virtual ICollection<jntuh_college_overall_faculty_studentratio> jntuh_college_overall_faculty_studentratio { get; set; }
        public virtual ICollection<jntuh_college_overall_faculty_studentratio> jntuh_college_overall_faculty_studentratio1 { get; set; }
        public virtual ICollection<jntuh_college_payment> jntuh_college_payment { get; set; }
        public virtual ICollection<jntuh_college_payment> jntuh_college_payment1 { get; set; }
        public virtual ICollection<jntuh_college_paymentoffee> jntuh_college_paymentoffee { get; set; }
        public virtual ICollection<jntuh_college_paymentoffee> jntuh_college_paymentoffee1 { get; set; }
        public virtual ICollection<jntuh_college_paymentoffee_type> jntuh_college_paymentoffee_type { get; set; }
        public virtual ICollection<jntuh_college_paymentoffee_type> jntuh_college_paymentoffee_type1 { get; set; }
        public virtual ICollection<jntuh_college_pgcourse_faculty> jntuh_college_pgcourse_faculty { get; set; }
        public virtual ICollection<jntuh_college_pgcourse_faculty> jntuh_college_pgcourse_faculty1 { get; set; }
        public virtual ICollection<jntuh_college_pgcourses> jntuh_college_pgcourses { get; set; }
        public virtual ICollection<jntuh_college_pgcourses> jntuh_college_pgcourses1 { get; set; }
        public virtual ICollection<jntuh_college_placement> jntuh_college_placement { get; set; }
        public virtual ICollection<jntuh_college_placement> jntuh_college_placement1 { get; set; }
        public virtual ICollection<jntuh_college_principal_director> jntuh_college_principal_director { get; set; }
        public virtual ICollection<jntuh_college_principal_director> jntuh_college_principal_director1 { get; set; }
        public virtual ICollection<jntuh_college_principal_ratified> jntuh_college_principal_ratified { get; set; }
        public virtual ICollection<jntuh_college_principal_ratified> jntuh_college_principal_ratified1 { get; set; }
        public virtual ICollection<jntuh_college_principal_registered> jntuh_college_principal_registered { get; set; }
        public virtual ICollection<jntuh_college_principal_registered> jntuh_college_principal_registered1 { get; set; }
        public virtual ICollection<jntuh_college_rti_complaints> jntuh_college_rti_complaints { get; set; }
        public virtual ICollection<jntuh_college_rti_complaints> jntuh_college_rti_complaints1 { get; set; }
        public virtual ICollection<jntuh_college_rti_details> jntuh_college_rti_details { get; set; }
        public virtual ICollection<jntuh_college_rti_details> jntuh_college_rti_details1 { get; set; }
        public virtual ICollection<jntuh_college_sports> jntuh_college_sports { get; set; }
        public virtual ICollection<jntuh_college_sports> jntuh_college_sports1 { get; set; }
        public virtual ICollection<jntuh_college_staticdata_modifications> jntuh_college_staticdata_modifications { get; set; }
        public virtual ICollection<jntuh_college_staticdata_modifications> jntuh_college_staticdata_modifications1 { get; set; }
        public virtual ICollection<jntuh_college_status> jntuh_college_status { get; set; }
        public virtual ICollection<jntuh_college_status> jntuh_college_status1 { get; set; }
        public virtual ICollection<jntuh_college_teaching_faculty_position> jntuh_college_teaching_faculty_position { get; set; }
        public virtual ICollection<jntuh_college_teaching_faculty_position> jntuh_college_teaching_faculty_position1 { get; set; }
        public virtual ICollection<jntuh_college_terms_accepted> jntuh_college_terms_accepted { get; set; }
        public virtual ICollection<jntuh_college_terms_accepted> jntuh_college_terms_accepted1 { get; set; }
        public virtual ICollection<jntuh_college_type> jntuh_college_type { get; set; }
        public virtual ICollection<jntuh_college_type> jntuh_college_type1 { get; set; }
        public virtual ICollection<jntuh_college_users> jntuh_college_users { get; set; }
        public virtual ICollection<jntuh_college_users> jntuh_college_users1 { get; set; }
        public virtual ICollection<jntuh_college_users> jntuh_college_users2 { get; set; }
        public virtual ICollection<jntuh_college_women_protection_cell> jntuh_college_women_protection_cell { get; set; }
        public virtual ICollection<jntuh_college_women_protection_cell> jntuh_college_women_protection_cell1 { get; set; }
        public virtual ICollection<jntuh_college_women_protection_cell_complaints> jntuh_college_women_protection_cell_complaints { get; set; }
        public virtual ICollection<jntuh_college_women_protection_cell_complaints> jntuh_college_women_protection_cell_complaints1 { get; set; }
        public virtual ICollection<jntuh_committee_observations> jntuh_committee_observations { get; set; }
        public virtual ICollection<jntuh_committee_observations> jntuh_committee_observations1 { get; set; }
        public virtual ICollection<jntuh_committee_submission> jntuh_committee_submission { get; set; }
        public virtual ICollection<jntuh_computer_student_ratio_norms> jntuh_computer_student_ratio_norms { get; set; }
        public virtual ICollection<jntuh_computer_student_ratio_norms> jntuh_computer_student_ratio_norms1 { get; set; }
        public virtual ICollection<jntuh_course_affiliation_status> jntuh_course_affiliation_status { get; set; }
        public virtual ICollection<jntuh_course_affiliation_status> jntuh_course_affiliation_status1 { get; set; }
        public virtual ICollection<jntuh_dataentry_allotment> jntuh_dataentry_allotment { get; set; }
        public virtual ICollection<jntuh_dataentry_allotment> jntuh_dataentry_allotment1 { get; set; }
        public virtual ICollection<jntuh_dataentry_allotment> jntuh_dataentry_allotment2 { get; set; }
        public virtual ICollection<jntuh_degree> jntuh_degree { get; set; }
        public virtual ICollection<jntuh_degree> jntuh_degree1 { get; set; }
        public virtual ICollection<jntuh_degree_type> jntuh_degree_type { get; set; }
        public virtual ICollection<jntuh_degree_type> jntuh_degree_type1 { get; set; }
        public virtual ICollection<jntuh_department> jntuh_department { get; set; }
        public virtual ICollection<jntuh_department> jntuh_department1 { get; set; }
        public virtual ICollection<jntuh_designation> jntuh_designation { get; set; }
        public virtual ICollection<jntuh_designation> jntuh_designation1 { get; set; }
        public virtual ICollection<jntuh_desirable_requirement_type> jntuh_desirable_requirement_type { get; set; }
        public virtual ICollection<jntuh_desirable_requirement_type> jntuh_desirable_requirement_type1 { get; set; }
        public virtual ICollection<jntuh_district> jntuh_district { get; set; }
        public virtual ICollection<jntuh_district> jntuh_district1 { get; set; }
        public virtual ICollection<jntuh_documents_required> jntuh_documents_required { get; set; }
        public virtual ICollection<jntuh_documents_required> jntuh_documents_required1 { get; set; }
        public virtual ICollection<jntuh_download> jntuh_download { get; set; }
        public virtual ICollection<jntuh_download> jntuh_download1 { get; set; }
        public virtual ICollection<jntuh_edep_equipment> jntuh_edep_equipment { get; set; }
        public virtual ICollection<jntuh_edep_equipment> jntuh_edep_equipment1 { get; set; }
        public virtual ICollection<jntuh_education_category> jntuh_education_category { get; set; }
        public virtual ICollection<jntuh_education_category> jntuh_education_category1 { get; set; }
        public virtual ICollection<jntuh_enclosures> jntuh_enclosures { get; set; }
        public virtual ICollection<jntuh_enclosures> jntuh_enclosures1 { get; set; }
        public virtual ICollection<jntuh_error_log> jntuh_error_log { get; set; }
        public virtual ICollection<jntuh_error_log> jntuh_error_log1 { get; set; }
        public virtual ICollection<jntuh_facility_status> jntuh_facility_status { get; set; }
        public virtual ICollection<jntuh_facility_status> jntuh_facility_status1 { get; set; }
        public virtual ICollection<jntuh_faculty_category> jntuh_faculty_category { get; set; }
        public virtual ICollection<jntuh_faculty_category> jntuh_faculty_category1 { get; set; }
        public virtual ICollection<jntuh_faculty_education> jntuh_faculty_education { get; set; }
        public virtual ICollection<jntuh_faculty_education> jntuh_faculty_education1 { get; set; }
        public virtual ICollection<jntuh_faculty_student_ratio_norms> jntuh_faculty_student_ratio_norms { get; set; }
        public virtual ICollection<jntuh_faculty_student_ratio_norms> jntuh_faculty_student_ratio_norms1 { get; set; }
        public virtual ICollection<jntuh_faculty_subjects> jntuh_faculty_subjects { get; set; }
        public virtual ICollection<jntuh_faculty_subjects> jntuh_faculty_subjects1 { get; set; }
        public virtual ICollection<jntuh_faculty_type> jntuh_faculty_type { get; set; }
        public virtual ICollection<jntuh_faculty_type> jntuh_faculty_type1 { get; set; }
        public virtual ICollection<jntuh_ffc_cluster_emails> jntuh_ffc_cluster_emails { get; set; }
        public virtual ICollection<jntuh_ffc_external_auditor_groups> jntuh_ffc_external_auditor_groups { get; set; }
        public virtual ICollection<jntuh_ffc_external_auditor_groups> jntuh_ffc_external_auditor_groups1 { get; set; }
        public virtual ICollection<jntuh_grc_designation> jntuh_grc_designation { get; set; }
        public virtual ICollection<jntuh_grc_designation> jntuh_grc_designation1 { get; set; }
        public virtual ICollection<jntuh_infrastructure_parameters> jntuh_infrastructure_parameters { get; set; }
        public virtual ICollection<jntuh_infrastructure_parameters> jntuh_infrastructure_parameters1 { get; set; }
        public virtual ICollection<jntuh_inspection_phase> jntuh_inspection_phase { get; set; }
        public virtual ICollection<jntuh_inspection_phase> jntuh_inspection_phase1 { get; set; }
        public virtual ICollection<jntuh_internet_bandwidth_norms> jntuh_internet_bandwidth_norms { get; set; }
        public virtual ICollection<jntuh_internet_bandwidth_norms> jntuh_internet_bandwidth_norms1 { get; set; }
        public virtual ICollection<jntuh_land_category> jntuh_land_category { get; set; }
        public virtual ICollection<jntuh_land_category> jntuh_land_category1 { get; set; }
        public virtual ICollection<jntuh_land_registration_type> jntuh_land_registration_type { get; set; }
        public virtual ICollection<jntuh_land_registration_type> jntuh_land_registration_type1 { get; set; }
        public virtual ICollection<jntuh_land_type> jntuh_land_type { get; set; }
        public virtual ICollection<jntuh_land_type> jntuh_land_type1 { get; set; }
        public virtual ICollection<jntuh_menu> jntuh_menu { get; set; }
        public virtual ICollection<jntuh_menu> jntuh_menu1 { get; set; }
        public virtual ICollection<jntuh_miscellaneous_parameters> jntuh_miscellaneous_parameters { get; set; }
        public virtual ICollection<jntuh_miscellaneous_parameters> jntuh_miscellaneous_parameters1 { get; set; }
        public virtual ICollection<jntuh_newsevents> jntuh_newsevents { get; set; }
        public virtual ICollection<jntuh_newsevents> jntuh_newsevents1 { get; set; }
        public virtual ICollection<jntuh_other_information_type> jntuh_other_information_type { get; set; }
        public virtual ICollection<jntuh_other_information_type> jntuh_other_information_type1 { get; set; }
        public virtual ICollection<jntuh_payment_mode> jntuh_payment_mode { get; set; }
        public virtual ICollection<jntuh_payment_mode> jntuh_payment_mode1 { get; set; }
        public virtual ICollection<jntuh_phd_subject> jntuh_phd_subject { get; set; }
        public virtual ICollection<jntuh_phd_subject> jntuh_phd_subject1 { get; set; }
        public virtual ICollection<jntuh_printers_norms> jntuh_printers_norms { get; set; }
        public virtual ICollection<jntuh_printers_norms> jntuh_printers_norms1 { get; set; }
        public virtual ICollection<jntuh_program_type> jntuh_program_type { get; set; }
        public virtual ICollection<jntuh_program_type> jntuh_program_type1 { get; set; }
        public virtual ICollection<jntuh_qualification> jntuh_qualification { get; set; }
        public virtual ICollection<jntuh_qualification> jntuh_qualification1 { get; set; }
        public virtual ICollection<jntuh_registered_faculty> jntuh_registered_faculty { get; set; }
        public virtual ICollection<jntuh_registered_faculty> jntuh_registered_faculty1 { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education> jntuh_registered_faculty_education { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education> jntuh_registered_faculty_education1 { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education_oldfaculty> jntuh_registered_faculty_education_oldfaculty { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education_oldfaculty> jntuh_registered_faculty_education_oldfaculty1 { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education11> jntuh_registered_faculty_education11 { get; set; }
        public virtual ICollection<jntuh_registered_faculty_education11> jntuh_registered_faculty_education111 { get; set; }
        public virtual ICollection<jntuh_registered_faculty_experience> jntuh_registered_faculty_experience { get; set; }
        public virtual ICollection<jntuh_registered_faculty_experience> jntuh_registered_faculty_experience1 { get; set; }
        public virtual ICollection<jntuh_registered_faculty_experience_log> jntuh_registered_faculty_experience_log { get; set; }
        public virtual ICollection<jntuh_registered_faculty_experience_log> jntuh_registered_faculty_experience_log1 { get; set; }
        public virtual ICollection<jntuh_registered_faculty_oldfaculty> jntuh_registered_faculty_oldfaculty { get; set; }
        public virtual ICollection<jntuh_registered_faculty_oldfaculty> jntuh_registered_faculty_oldfaculty1 { get; set; }
        public virtual ICollection<jntuh_reinspection_college_laboratories_deficiency> jntuh_reinspection_college_laboratories_deficiency { get; set; }
        public virtual ICollection<jntuh_reinspection_registered_faculty> jntuh_reinspection_registered_faculty { get; set; }
        public virtual ICollection<jntuh_reinspection_registered_faculty> jntuh_reinspection_registered_faculty1 { get; set; }
        public virtual ICollection<jntuh_reinspection_registered_faculty_education> jntuh_reinspection_registered_faculty_education { get; set; }
        public virtual ICollection<jntuh_reinspection_registered_faculty_education> jntuh_reinspection_registered_faculty_education1 { get; set; }
        public virtual ICollection<jntuh_shift> jntuh_shift { get; set; }
        public virtual ICollection<jntuh_shift> jntuh_shift1 { get; set; }
        public virtual ICollection<jntuh_society_other_colleges> jntuh_society_other_colleges { get; set; }
        public virtual ICollection<jntuh_society_other_colleges> jntuh_society_other_colleges1 { get; set; }
        public virtual ICollection<jntuh_society_other_locations_colleges> jntuh_society_other_locations_colleges { get; set; }
        public virtual ICollection<jntuh_society_other_locations_colleges> jntuh_society_other_locations_colleges1 { get; set; }
        public virtual ICollection<jntuh_software_norms> jntuh_software_norms { get; set; }
        public virtual ICollection<jntuh_software_norms> jntuh_software_norms1 { get; set; }
        public virtual ICollection<jntuh_specialization> jntuh_specialization { get; set; }
        public virtual ICollection<jntuh_specialization> jntuh_specialization1 { get; set; }
        public virtual ICollection<jntuh_sports_type> jntuh_sports_type { get; set; }
        public virtual ICollection<jntuh_sports_type> jntuh_sports_type1 { get; set; }
        public virtual ICollection<jntuh_stackholder_type> jntuh_stackholder_type { get; set; }
        public virtual ICollection<jntuh_stackholder_type> jntuh_stackholder_type1 { get; set; }
        public virtual ICollection<jntuh_state> jntuh_state { get; set; }
        public virtual ICollection<jntuh_state> jntuh_state1 { get; set; }
        public virtual ICollection<jntuh_transport_type> jntuh_transport_type { get; set; }
        public virtual ICollection<jntuh_transport_type> jntuh_transport_type1 { get; set; }
        public virtual ICollection<jntuh_university> jntuh_university { get; set; }
        public virtual ICollection<jntuh_university> jntuh_university1 { get; set; }
        public virtual ICollection<jntuh_water_type> jntuh_water_type { get; set; }
        public virtual ICollection<jntuh_water_type> jntuh_water_type1 { get; set; }
        public virtual ICollection<jntuh_year_in_degree> jntuh_year_in_degree { get; set; }
        public virtual ICollection<jntuh_year_in_degree> jntuh_year_in_degree1 { get; set; }
        public virtual my_aspnet_applications my_aspnet_applications { get; set; }
        public virtual my_aspnet_membership my_aspnet_membership { get; set; }
        public virtual my_aspnet_profiles my_aspnet_profiles { get; set; }
        public virtual ICollection<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
    }
}
