//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_roles
    {
        public my_aspnet_roles()
        {
            this.my_aspnet_usersinroles = new HashSet<my_aspnet_usersinroles>();
        }
    
        public int id { get; set; }
        public int applicationId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
    }
}
