//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_aspnet_profiles
    {
        public int userId { get; set; }
        public string valueindex { get; set; }
        public string stringdata { get; set; }
        public byte[] binarydata { get; set; }
        public System.DateTime lastUpdatedDate { get; set; }
    
        public virtual my_aspnet_users my_aspnet_users { get; set; }
    }
}
