//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_automobile
    {
        public int Sno { get; set; }
        public string Degree { get; set; }
        public string Department { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Semester { get; set; }
        public string LabCode { get; set; }
        public string LabName { get; set; }
        public string NameoftheEquipment { get; set; }
        public string NoofUnitsRequired { get; set; }
        public string Remarks { get; set; }
    }
}
