//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAAASSCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_login_logout
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IPAddress { get; set; }
        public string SessionId { get; set; }
        public Nullable<System.DateTime> Login { get; set; }
        public Nullable<System.DateTime> Logout { get; set; }
        public bool isOnline { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
    }
}
